### ISSUE TITLE
2 things, help

### ISSUE THREAD

**Issue by seli11** [dillbyrne/random-agent-spoofer#118]
1- can you add the option to rotate the language, local time, and browser scren size every request? 
 2- if i choose  safari on mac, i tested this on 
 http://browserspy.dk/flash.php   i use windows,        
 this say  platform = windows! should say platform=mac, i can't  disable flash for youtube, the best user agent thank you, and sory for my bad english

**Comment by dillbyrne** [comment]
Hello @seli11 

I have issues already open for addressing the date and time, language and screen size. See #66 and #67 . 
For the language it is not as simple as putting in what ever your current language settings are. They have to match the **exact** headers sent by a browser which is downloaded for that locale otherwise the user will stand out. Also it has to be done for every browser profile in the addon and they represent these values differently.

If you would like to help with this  you can visit [http://browserspy.dk/accept.php](http://browserspy.dk/accept.php) in all the browsers you have and paste the accept language setting in the #67 . Note the browsers you use should be set in your native language by default when you downloaded them. This point is important because the [relative quality](http://it.i88.ca/2013/05/relative-quality-factor-in-http-accept.html) part of the accept language header could have been changed if you changed the browser's language settings so only defaults are useful.

 
As for the screen size and date and time, they are set per request if random options are selected. The date strings need some more work which I have to set up a VM and change go through each timezone to get the time zone abbreviation but in terms of time offsets the work is done already.

[Using flash is not recommended](http://www.cvedetails.com/vulnerability-list/vendor_id-53/product_id-6761/Adobe-Flash-Player.html) and I do not intend to support flash. Using flash will allow sites to bypass many protection mechanisms of many addons. Try disabling flash and trying the test again.

Youtube now works with html5 and does not require flash. In RAS you can use the whitelist which has a youtube rule in the whitelist by default to allow the canvas element. Alternatively  if you choose the `Sony Experia E` Android profile you can continue to block the canvas and use the mobile version flash free.


What version of safari on mac were you spoofing ? . I highly suspect it was flash that was bypassing it.

You can see the mac profiles [here](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json) There is no mention of windows in the Mac profiles.
