### ISSUE TITLE
Canvas protection fails randomly

### ISSUE THREAD

**Issue by danielcra** [dillbyrne/random-agent-spoofer#121]
Canvas protection fails randomly. The page at https://www.browserleaks.com/canvas sometimes shows a fingerprint and sometimes it doesn't, depending on how I load it (retry several times: click bookmark, press return in address bar, use menu at bottom left, click reload in browser). I did clear my browser cache and restarted FF several times ;-)
My settings are: canvas, webgl, webrtc disabled, the rest left to default (not disabled).
Whitelist: youtube.com
Firefox 34 on Win 7 64
RAS version 0.9.5.0 downloaded as .xpi

**Comment by dillbyrne** [comment]
Hello @danielcra 


Thanks for the bug report. I can confirm this when visiting the page and then another link and returning back to that page. 

Can you describe other steps which trigger it. 

I will try to have a fix out for this soon.

**Comment by dillbyrne** [comment]
@danielcra Using the navigation buttons to move between a visited page or a new one no longer stops the script. This will disable the BFCache completly but it was the only thing I could get to work. If anyone knows of a better way feel free to have a go or let me know. I can't see it causing much problems besides the user having to refetch the page each time, this is what forces the the script to be loaded again.



Can you tell me all of the different ways that you managed to produce this so I can check if it is fully prevented. 

Then afterwards can you try this test version https://github.com/dillbyrne/random-agent-spoofer/releases/download/0.9.5.1-test1/random-agent-spoofer.xpi to see if it fixes the issue. 

Thanks

**Comment by dillbyrne** [comment]
'network.http.use-cache = false' has the same effect as the fix above and is a better option than forcing it in the script.

**Comment by danielcra** [comment]
I tried again but I could not find any deterministic sequence of actions that causes the canvas tracking to work.

I then installed RA 0.9.5.1 and ticked only canvas protection. I could still reproduce the issue.

I then set network.http.use-cache = false and could no longer reproduce the issue.

Why is canvas tracking related to cache?

**Comment by dillbyrne** [comment]
@danielcra the steps I took to produce the issue in 0.9.5.0 were:
1 check the canvas option and visit the canvas test page. 
2 click on another link to the left such as display ip address
3 press back in the browser to return to the previous page.

in 0.9.5.0 this showed unspoofed values on the canvas test page.
in 0.9.5.1 it showed the spoofed values on the canvas test page.

What steps did you take with 0.9.5.1 to reproduce it ? Can you try it in a fresh profile.


Now to your question as to why this occurs. When you visit a page in firefox it is added to the bfcache ( backwards forwards cache). This allows you to go back and forward between visited pages quickly and the content of the pages is cached. What is happening in this case is that ajax is being run each time we land on the page but our script is still cached from the previous time so it is not being re added to the page and therefore the values are not being spoofed.

Disabling the cache forces the browser to request the page again and our script then gets injected again.

**Comment by dillbyrne** [comment]
You were correct about 0.9.5.1 For some reason it worked when I tested it yesterday but it no longer seems to work so I have made a new update to force the browser cache off by default while the RAS is installed by setting `network.http.use-cache = false`. 

Since this affects the whole script injection it looks like this will be a requirement in the github version and the AMO version if they allow any script injection. 


You can get the release here https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.1

**Comment by danielcra** [comment]
I can confirm the issue is solved after installing the new 0.9.5.1 version and enabling canvas protection.
Thanks for the prompt response. Excellent work!

Just as a future improvement, it would be great if one could still use the cache and still get canvas protection. And, no, I do not have a brilliant idea how to implement that ;-)

**Comment by dillbyrne** [comment]
@danielcra Thanks. I agree the fix is not ideal I agree but having functional canvas protection outweighs the need for the cache. If I can find another way to fix it that does not require loosing the ability to allow caching I will be sure to add it.

**Comment by Rudd-O** [comment]
It really was not a responsible thing to do to blanket disable the browser cache without giving the user a choice.  Yes, in your latest extension, the tick box "disable browser cache" has NO effect, nor is the browser cache disabled only when canvas protection is enabled.

It was also not a responsible thing to change the code and remove migration code that was perfectly okay, then require users to.  I have hundreds of browsers to upgrade now, and this manual upgrade you suggest in your releases page is humanly impossible to do.

Please unbreak my computers.

**Comment by dillbyrne** [comment]
@Rudd-O 

Actually it was the responsible thing to do as it addresses a bug in the script injection capability used by RAS, sure the fix is not ideal as I have noted above but I have not found another way to address it yet. It ensured that users who upgraded were protected from leaks by forcing a reload of the page each time.

The "disable browser cache" option in 0.9.5.1 is for different cache options. Specifically the memory cache and disk cache. The cache I set as disabled in 0.9.5.1 was the network cache which seems to take precedent over the other caches. So that explains why you are not seeing changes.

The next version has options for all the cache options with the network cache disabled by default and recommended to keep it that way. You can see the cache options in the screenshot below
![ras_preview](https://cloud.githubusercontent.com/assets/2903711/6760225/a27f27ae-cf3e-11e4-905a-d47bf6a7a8e6.png)

I remove the migration code because it is only relevant from one version to the next. Lots changes between RAS releases. I aim to ensure a smooth upgrade from the last release to the current release. That is it. Most of the big changes are to the core of how RAS works and it would take forever to do a release if I had to ensure it was compatible will all the older versions .

As I state in the release page you can either upgrade from one to the next and so on up to the present one or remove it and install the current version brand new.

 To be fair **I listed the changes in the release page ** which linked to this issue which you could read the thread and see the exact preference and the rationale behind the choice and you still chose to install it.

**Comment by dillbyrne** [comment]
I have updated the canvas code and it no longer relies on disabling the firefox cache by default

**Comment by Rudd-O** [comment]
Can you explain what changed in the canvas code that made the cache irrelevant?  Thanks.

Also, I know there's tracking of if-modified-since which has been a thing since, like, ages.  What protections does RAS deploy against that?  Thanks.
