### ISSUE TITLE
Gecko mode (enhancement)

### ISSUE THREAD

**Issue by gitoss** [dillbyrne/random-agent-spoofer#133]
Great extension, one suggestion though: Add a checkbox "gecko mode" that only enables gecko-based browsers (firefox, palemoon, iceweasel, seamonkey, ...). At the moment, you have to scroll through the whole long list and disable every non-gecko browser one by one.

The reason is that using this proposed feature in conjunction with "desktop only" has the least potential of screwing up the rendering by taking the wrong turn at browser branches. Imho just spoofing the gecko brand and the operating system is good enough for a minimal setup.

**Comment by dillbyrne** [comment]
Hello @gitoss 

Thanks for the support. 

The desired functionality would be best achieved by using a custom `useragents.json` file. I can help you if you require. 

Or alternatively you could set the exclude option for each profile.

There are already many checks happening each time a profile is switched and I do not want to add any more if I can avoid it because each check slows it down.

**Comment by gitoss** [comment]
Thanks, makes sense. I'll drop this in favor of a better whitelist gui (see other ticket) to quickly un-break sites that cause problems. Keep up the good work!

**Comment by dillbyrne** [comment]
@gitoss Thanks. If you would still like to have a custom version I can help you with it.
