### ISSUE TITLE
Web-P/M not working when in Chrome/Opera UA mode

### ISSUE THREAD

**Issue by ProgerXP** [dillbyrne/random-agent-spoofer#143]
This is direct consequence of #96. When RAS spoofs UA to be Chrome or Opera >12 it will also send Accept headers to allow for Chrome-specific media formats. For example, if you visit Play Store you will see that all pictures are broken. This makes RAS unusable when it's spoofing Chrome and given that Firefox is only a small fraction of all UAs this happens 70% of all time.

On the other hand, I can't see how to amend this because changing Accept won't look genuine. Any ideas?

**Comment by Gemkhy** [comment]
Hi ProgerXP, sorry if i will post here just to contact you, Please Contact me or reply on email. i already send message in your gmail. please check. Regarding Khan Online: Server emulator. my email: gemkhy@yahoo.com.ph

Thanks! looking forward for your positive response.
you can delete this message after your read . thanks

**Comment by dillbyrne** [comment]
@ProgerXP  The only options I can think of are to whitelist the affected sites, exclude problematic profiles or in this case avoid the play store and use https://github.com/onyxbits/Raccoon instead

Other than the above there is not much that can be done. Changing the accept headers would make the browser stand out too much so that is not an option. 

@Gemkhy this is not a personal message board. Users watching this addon have all now received your message. Please do not do this again, if you do I will block you. You do not need to reply to this unless it is related to the addon in some way.

**Comment by ProgerXP** [comment]
> to whitelist the affected sites, exclude problematic profiles 

I'd do this but it's surprising how many and diverse sites have this feature of optimizing for Chrome. Sadly I can't think of a solution either but this problem gets in a way of normal web surfing.

> Please do not do this again, if you do I will block you. You do not need to reply to this unless it is related to the addon in some way.

I'd be grateful if you could just remove his message.

**Comment by dillbyrne** [comment]
@ProgerXP You could always compile a version of RAS with only firefox / palemoon / iceweasel profiles if you want. There is not really much I can do about sites optimizing for chrome. 

I have deleted the comment.

**Comment by ProgerXP** [comment]
> You could always compile a version of RAS with only firefox / palemoon / iceweasel profiles if you want. 

Problem is I don't want to exclude Chrome/Opera from the list of spoofed UAs, they are a good share of all UAs out there. But the only workaround to this I see is built-in support for Web-P, which is somewhat optimistic (and isn't the feature I'd hold my breath for).

Anyway, just a food for thoughts.
