### ISSUE TITLE
RAS overrides firefox preferences without any user input.

### ISSUE THREAD

**Issue by Gizzah** [dillbyrne/random-agent-spoofer#151]
I noticed a strange and unnecessary behaviour. The settings "Disable browsing and download history" and "Use standard font set" are working as intended, but it's fairly easy to get the desired effect in the firefox preferences without using RAS. In the case of setting custom fonts, it's actually the more desirable way, because you can decide which fonts to use, RAS only offers the standard font set.

The problem is that RAS ignores the settings in the firefox preferences after it get disabled and enabled again and overrides them without any warning. If you disable the standard font set option in RAS and use the firefox preferences to choose your own custom font by unchecking the "Allow pages to choose their own fonts, instead of my selections above" option, you will notice that RAS overrides your selection as soon as you restart it, thus allowing pages to use their own fonts again.

This is entirely unnecessary, the add-on shouldn't override user preferences when a RAS feature is disabled. I don't know if these two options are the only ones where this happens, but a disabled feature shouldn't interfere with user settings.

**Comment by dillbyrne** [comment]
Hello @Gizzah 

Some background on this.

When I designed RAS I wanted a quick way to enable/disable all the options applied by the addon. As such I implemented a toggle system which kept track of the choices for each preference while the addon state was toggled off.

 The meant restoring the changes made by RAS to a working state while the addon was disabled but still keeping track of the options selected to reapply when it was enabled. To be sure the disabled state worked all the preferences except the ones storing the states were reset to their defaults. This ensured a guaranteed working state when the addon was disabled. 

When the addon was  re/enabled RAS applied the preferences stored in the intermediary state to the ones that were reset to default. So that is why RAS would overwrite preferences when it has been toggled on or off.

Since many users find this confusing or  undesirable I have removed the toggle based system with my latest [commit](https://github.com/dillbyrne/random-agent-spoofer/commit/4d34659565b1274e77d3b8edd153fc7f8ad76df2). See  the last comment #27 for more details . As such I will now close this issue.
