### ISSUE TITLE
UI/UX improvement

### ISSUE THREAD

**Issue by alct** [dillbyrne/random-agent-spoofer#154]
Hello,

First of all, thanks for this add-on, I use it extensively. Over the past few years, I recommended it countless times during security workshops (privacy cafés, crypto parties, ,...). I have noticed a trend among less tech-savvy people: they get lost in the options. I do believe that updating the wording slightly and tweaking the UI/X could make things better.

Before dedicating time to this, I'd like to be sure that it's something you're interested into. I have (very) little experience with Firefox extensions but I had a look into it and so far, it's seems like it's just a matter of updating the HTML, CSS, and a little bit of JS. Which I can do in snap.

## PoC or GTFO

Demo: http://loconte.be/tmp/random-agent-spoofer/?1426522785
![screenshot from 2015-03-17 01 04 27](https://cloud.githubusercontent.com/assets/360770/6679002/9ce8ecf2-cc42-11e4-8e0c-2adf5425fca1.png)
![screenshot from 2015-03-17 01 04 45](https://cloud.githubusercontent.com/assets/360770/6679009/a595afc0-cc42-11e4-9458-40209b77efcc.png)
![screenshot from 2015-03-17 01 04 58](https://cloud.githubusercontent.com/assets/360770/6679019/b5b597bc-cc42-11e4-9c5b-c622a23498bb.png)

### Overall:

- clean look: remove everything that isn't essential (in the sense that it provides an information/visual structure) such as the rounded corners, borders, etc. ;
- tabs use all the available horizontal space ;
- titles that provide redundant information are removed (such as “Choose A Browser Profile”), and the visual weight of the tabs title is increased ;
- overall readability is improved by increasing the font size and increasing the contrast between the fore and the background ;
- depending on the UA being spoofed or not, the background color of the nav menu is either blue or black (to mimic the behavior of the icon) ;

### “Profile” tab:

- “Default” isn't explicit. It could mean “there's a spoofed UA by default”, “there's no spoofed UA”, “that's the default spoofed UA set by the user”. It is reworded in “Real UA” ;
- the “(all)” part of “Random (all)” is useless. It's either “Random (specific)”, “Random” or “Real” ;
- the “Random (mobile)” is just a place holder (I've seen that it is a feature request) ;
- the “timer” field is hidden and shown only if one the random options is chosen (click on “Random” or “Random (specific)” to give it a try);
- “Change random profile on time interval” is reworded in “Change UA dynamically” ;
- the selected UA is bold and blue (when "Real UA" it is black) ;
- the exclude checkboxes are hidden by default, they are only useful when a random option is chosen  ;
- rather than having an inexplicit “Exclude” header that appears out of nowhere, behaves like a title but does nothing, we create an option to toggle the exclude checkboxes ;
- a visual structure is created around the titles of the UA list (extending the click zone in the same shot)  ;
- inside the titles of the UA list, contents of the same informational weight are structured as well (“+” and “-” are isolated, always at the same position regardless of the size of the title) ;
- the first element of the UA list is expanded in order to give a visual clue to the user that it is either one of the four options at the top or anything else in the list ;
- when a UA is selected, a visual clue is added to the parent title (background color) in order to help the user find the element he has chosen back (click on “Mac browsers” > “Chrome”, than back on “Windows browsers”).

(titles other than “Windows browsers” and “Mac browsers” are just placeholders, the list of available UA is reduced for the purpose of the PoC)

### “Help” tab:

- rather than having an “help” button lost deep at the bottom of a tab, a help tab containing meaningful information (such as links to the github page, wiki,...) is created.

### As for the other tabs

There's room for improvement as well. I'm waiting for your feedback prior going further.

Disclaimer: I used jQuery because it's just a PoC, if needed I'll rewrite the code to vanilla JS.

What do you think?

**Comment by valencik** [comment]
Nice work! I'd love to see these kind of improvements get accepted.

**Comment by dillbyrne** [comment]
@alct I love it, great work :+1:  and thank you for the time you put into it. I'll aim to get it included for the upcoming release. I initially kept it plain so it would look ok with custom linux themes such as dark ones but your version is far more cleaner and simpler and anything that helps make it more usable and reduces confusion is a plus.

I'll be a bit busy for a few days but I'll be in touch before I start working on it and we can work on it together.

**Comment by alct** [comment]
Great :) Ping me when needed. My mail address is on my website ; I go by alct on (irc) freenode.

**Comment by dillbyrne** [comment]
I have made a start on this and I have a good bit of the changes added, I still have to do some work so the changes are applied to the UI when a selection is made from the context menu.

**Comment by alct** [comment]
Make sure to get the latest version, I slightly updated the code. I've got some questions regarding the headers tabs, some options are unclear and I have a hard time rewording it.

**Comment by dillbyrne** [comment]
@alct I will do thanks, Your PoC has been a big help! :+1: . I'm trying to keep it as much like your code where possible, though I need to do the JS stuff myself as it is not jquery and to integrate with existing code.

 I'm not sure there is much that can be done with the header names as they are standard names. Which options do you feel are unclear ?

**Comment by dillbyrne** [comment]
I have also added the same style used in the profiles tab to the whitelist.  

![ras_new_ui_whitelist_tab_preview](https://cloud.githubusercontent.com/assets/2903711/6722018/bd1d21de-cdcb-11e4-83c1-ac207a1a3c0c.png)

@alct I don't mind discussing this here in the interest of openness but if you would like I can PGP mail you or we can discuss it over [XMPP with OTR](https://dillbyrne.github.io/contact.html) .

**Comment by alct** [comment]
Let's do it here than ;)

### Headers tab

#### 1. Ambiguity around he various actions

* What does "Disable Authorization header" do exactly?
* DNT header (value: none or enabled), when "none" is selected, does it send the field at all or does it send a DNT: 0?

As for the following options, it is unclear why they are separated and what "Accept headers match the selected browser profile" means.

* "Send spoofed accepted documents", what HTTP header is it ? (I can't find any reference to it - [IANA](https://www.iana.org/assignments/message-headers/message-headers.xhtml), [W3](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
))
* "Send spoofed accepted encoding", what is the value used ?

#### 2. Drop list with two options

If the choice is binary (one value or another), we shouldn't use a drop list. I'll work on this part today.

P.S. looking at the screenshot, it looks like you're using the old version of the HTML/CSS (my bad, my server does heavy caching on this kind of ressource - here you go [HTML](https://gist.github.com/alct/c5502121dccb5358f21d), [CSS](https://gist.github.com/alct/b976832cfb7cfd0620d8))
P.S.² you'll see that this version of the HTML contains an updated "header" tab, don't pay attention to it as it's just a draft and I'll update it today

**Comment by alct** [comment]
P.S.³ Make sure to check the web version of this thread (the problem with the outdated CSS might come from the fact that I've updated my first comment to point to the version but that you received only one mail notification for the original message).

**Comment by dillbyrne** [comment]
>DNT header (value: none or enabled), when "none" is selected, does it send the field at all or does it send a DNT: 0?

Initially I planned to offer to the option randomize the headers such as `DNT` in addition to those already present so it was done as a dropdown to account for the additional options. As for how `DNT` is set, It is manually set it in Chrome.js like

```
            // DNT header
            if (PrefServ.getter("extensions.agentSpoof.dnt") == "none"){
                httpChannel.setRequestHeader("DNT","",false);
            }else{
                httpChannel.setRequestHeader("DNT","1",false);
            }
``` 

Sending a blank string when `none` is selected causes the header not to be sent at all and selecting enabled causes `1` to be sent asking the site not to track the user. As I mentioned above the initial plan was to also have a random option where it would randomly be sent thus changing the fingerprint, As not all the browsers send or support `DNT` I decided against it. I will be changing the `DNT` implementation to use the built in firefox prefs in future. 
 
I plan to improve the `referer` header with more options in #110 so I will keep that as a dropdown.

> What does "Disable Authorization header" do exactly?

It prevents the Authorization header from being sent 

https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side  

>As for the following options, it is unclear why they are separated and what "Accept headers match the selected browser profile" means.

They are separated as they are [defined by the selected profile](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json) and the separation and text above them is to emphasize this. 

The language header will eventually have a dropdown allowing users to choose the accept language #67 .

if accept headers are **not checked** the default firefox accept headers will be sent and **they will make the user stand out if the selected profile is not firefox or based on firefox** so that is why I have added the text above those options.

>   "Send spoofed accepted documents", what HTTP header is it (I can't find any reference to it - IANA, W3, Wikipedia) ? Is it actually "Accept", if so, what is the value used ?
    "Send spoofed accepted encoding", what is the value used ?


Yes accepted  documents is the Accept header (I should change this simply to Accept header)
Accept-Encodings along with the other accept headers are [defined by the selected profile](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json) in the useragents.json file.


>If the choice is binary (one value or another), we shouldn't use a drop list. I'll work on this part today.

I agree but for some options I need to keep the dropdowns, such as the `XFF` and `Via` ip inputs and the `referer` header option as I will be adding more to that.

I have been working from the version on your site :) .

As for the current progress I nearly have it working . I still need to get the tab colors switching and working correctly as it has to reflect changes set from the context menu too. I also have to do the code for the checkboxes too. The random mobile option needs to be implemented too but I will do that in #148 .
 
The only thing I'm not sure about is the `Toggle UA exclusion` I don't think that is needed since the checkboxes display property is toggled depending on if a random option is selected or not . I'm thinking instead to have `Exclude`  right aligned  beside each random profile option so it is above the checkboxes in each section. I feel this makes it clear that the checkboxes are for excluding those profiles.

What do you  think ?

**Comment by dillbyrne** [comment]
I have all the UI current proposals implemented with exception of the `Toggle UA exclusion` as I option to use the method mentioned in my previous post, which I updated with screenshots. 

I'll keep this issue open as I'm sure there is more we can improve on. In the meantime  I'll get working on the random mobile option.

**Comment by alct** [comment]
Hey,

Had an unplanned urgent mission, I couldn't work on it as scheduled, sorry. I'm back on Wednesday 25th. I'll have a look at your comments.

**Comment by dillbyrne** [comment]
@alct No worries. Have a look whenever you can.

**Comment by dillbyrne** [comment]
A screenshot showing the new icons and the temporary email option.
![ras_preview6](https://cloud.githubusercontent.com/assets/2903711/6962219/4caa6fa0-d92a-11e4-976c-da208b7f585f.png)

**Comment by dillbyrne** [comment]
I plan to release 0.9.5.2 in the next week or so because I want to get it out before firefox 38 is released and I want to get a limited version on AMO.  There are one or two things I want to fix with the UI and then I'll be happy enough to ship it.

@alct I'm trying to reduce the padding / margin above and below the profile items in each OS section to 0.5em and I can't seem to find where your setting that in the CSS.

The mouse is at the top area in question screenshot below 

![ras_preview6](https://cloud.githubusercontent.com/assets/2903711/7043261/327e373c-dde0-11e4-96a0-4e69e44a3935.png)

**Comment by alct** [comment]
I had to hack it here https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/js/optionspage.js#L237

When I'm done working on the markup, we'll be able to put it in `style.css`. We can't do it for the time being because the property is overridden by the JS (and that there's no clean way to target that peculiar element).

**Comment by alct** [comment]
(please use the following notation `.5em` in the code, no need for a leading 0 ;) )

**Comment by dillbyrne** [comment]
@alct Thanks.

**Comment by alct** [comment]
After merging #180, if you've got time, could you:

In the "whitelist" tab:

- reword the sentence from "Disable […]" to "Enable […]" ;
- uncheck the box by default ;
- when the box is unchecked, hide the "Profile" and "Rules" sections ;
- when the box is checked, show these sections.

In the "extras" tab:

- move "☑ Enable script injection" and the following sentence over the section ;
- implement the same mechanism as described above for the "Script Injection Options" section (hide, show,…).

? It be great and would allow me to finish the markup cleanup (together with fixing the few little issues introduced by #180).

P.S. #180 gets rid of the hack described [here](https://github.com/dillbyrne/random-agent-spoofer/issues/154#issuecomment-90882691)

**Comment by dillbyrne** [comment]
Sure I can change the whitelist preference and uncheck it by default and add any necessary upgrade code the handle the pref change. I'll do it when I get a chance , after I merge #180 

I would like to keep all the script injection options together in the same section. I have more extras sections planned such as a proxy section, a cookies section, a media/codec related section and so on. I want each section to be self contained as it looks cleaner. It also makes it easier to implement the AMO version as I can leave the script injection section in the addon and cross out the enable option. This allows users to see that it is disabled and see the related options that are not available as a result.

The whitelist on the otherhand is in its own tab. So I don't see the need to show and hide the options based on if it is enabled or not. A user is not going to be looking at the whitelist tab unless they intend to use it or edit it. Having to click the checkbox to show the expandable options which the user would then expand seems like overkill.

If there was more sections on the whitelist tab or if it contained other non whitelist related options then I could see the need for it but as it stands its not like the space is needed because there is nothing else on it but whitelist sections

**Comment by alct** [comment]
Here we go (#187).

Titles (`h2`) in the *headers*, *extras* and *whitelist* tabs have a different style than *profile* tab ones. This is done on purpose and I highly encourage leaving it this way. *Profile* tab titles have a different role than titles in other tabs (if we've got time, I'll replace them by `h3` and update the CSS accordingly - it will be invisible to the user, that's just for the sake of having a coherent markup).

After 0.9.5.2, I'll work on improving the *profile* tab further.

**Comment by alct** [comment]
I would also encourage to leave the titles in the *headers*, *extras* and *whitelist* tabs open (expanded).

**Comment by alct** [comment]
> if we've got time, I'll replace them by h3 and update the CSS accordingly - it will be invisible to the user, that's just for the sake of having a coherent markup

Done.

**Comment by dillbyrne** [comment]
Hey @alct Great job on this. :+1:  

I really appreciate your work on this but I would prefer to have the expanding sections visually the same as those on the profile tab. I think they look nicer and it promotes familiarity . This way we are not providing 2 visually different styles to display extendible content. 

I recognize that the content in the expandable sections differs but we already have the tabs and their headings to distinguish which content it which. This addresses the consistency of the expanding action itself.

>The reuse principle: The design should reuse internal and external components and behaviors, maintaining consistency with purpose rather than merely arbitrary consistency, thus reducing the need for users to rethink and remember.

>The structure principle: Design should organize the user interface purposefully, in meaningful and useful ways based on clear, consistent models that are apparent and recognizable to users, putting related things together and separating unrelated things, differentiating dissimilar things and making similar things resemble one another. The structure principle is concerned with overall user interface architecture.

source https://en.wikipedia.org/wiki/Principles_of_user_interface_design

I can change them if you would like or you can if you would prefer. Let me know and thanks again.

**Comment by dillbyrne** [comment]
I am happy enough with the present look and feel of the UI now and I feel that the objective of this issue has been addressed. I'm closing this issue now so I can focus on the remaining issues, translations and testing before releasing 0.9.5.2 .

@alct Thanks again for all your help on this. :+1:

**Comment by alct** [comment]
You did well, I was about to suggest to close the thread because it was getting quite lengthy.

Regarding the reuse principle, I'm well aware of it :)

Yet, even though I believe that the UI/UX is better than what is was (and will be easier to improve thanks to the mamrkup cleanup), I also believe that it's not optimal yet.

For instance, forcing the user to take an action (click) to expand a section right after he's just clicked to open a tab is counter productive IMO. While the expand mechanism does make sense on the *profile* tab because four options are already available without having to expand anything and the others are alternate options (it's one or another - the user can't chose several of them except for excluding UAs) and that there are many of them ; it does not in other tabs because it creates an additional step to achieve the purpose of the tab (setting options).

As for the styles, they're better but okey-ish.

Anyway, I don't want to fight it too much, I've been thinking about improvements for future releases, I'll see to put a PoC together in the coming weeks.

Let's get this 0.9.5.2 out there :)

**Comment by dillbyrne** [comment]
I'm working with the bigger picture in mind so while having them collapsed by default may seem unusual now it will save the user scrolling down a massive list of options when future sections are added and allow them to access the relevant section quickly by clicking it. 

Anyway I have work to do for 0.9.5.2 :smile:

**Comment by 0nse** [comment]
The redesign is a really nice addition. But either I am overlooking something or the option to turn off notifications has been dropped?

**Comment by 0nse** [comment]
The redesign is a really nice addition. But either I am overlooking something or the option to turn off notifications has been dropped?

**Comment by dillbyrne** [comment]
@0nse The notifications preference was moved to the about:addons page

![temp](https://cloud.githubusercontent.com/assets/2903711/7373673/d3f76f1c-edc5-11e4-9a7a-4ba0243bd8df.png)

**Comment by 0nse** [comment]
@dillbyrne that makes a lot more sense and I feel a bit stupid for having overlooked it. Thank you.

**Comment by dillbyrne** [comment]
@0nse No problem. I moved it there as it is not an option that changes very often. I'll add the changes to the wiki when I get a chance to update it.
