### ISSUE TITLE
Issues with the toolbar button

### ISSUE THREAD

**Issue by tegru** [dillbyrne/random-agent-spoofer#157]
Hello,

I think my problem needs some background info to make it more clear:
Well, I use extra add-on bar extensions to keep my Firefox window clean. After upgrading to Fx36 a problem has appeared with some (not RAS) add-on icons doubling their size... and off course the size of the toolbar too....

So I searched for a toolbar add-on that does not have this problem and found Puzzle Toolbars. However, this has another problem with some add-ons, including Random Agent Spoofer: its icon disappears randomly from the toolbar and when customizing Firefox UI.

It seems like the RAS button is implemented in some pretty non-standard way. For example. when you move it to the main toolbar in customizing mode, it shows as text not icon.
......
Overall, it's like "Wild Wild West" in the way add-ons implement their icon/button on Firefox. All of them behave differently. In this way Chrome add-ons behave much better.

**Comment by tegru** [comment]
Sorry, just upgraded to version 9.5.1 and it doesn't seem to have these problems. I'm new to GitHub and didn't find it at first... But why is only such an outdated version available on the Mozilla Add-on site?

Anyways, great add-on. Thanks.

**Comment by dillbyrne** [comment]
Hello @tegru .

Thanks for your support  

The reason for varying icon issues is due to the old widget code which as now been replaced by the ActionButton or ToggleButton .  The older version of RAS used the widget before the Australis UI change and it worked fine. Newer versions use the ActionButton and that is for the Australis version only.

As to the reason why the AMO version is so old. For a long time most of the changes I was making were to the script injection code which deals with things such as screen spoofing and date and timezone spoofing as well as the whitelist. 

AMO will not approve versions with the script injection code particularly the screen spoofing , as it can break a lot of sites. Personally I have not found it breaking any sites but I can see that it is a possibility so I understand their reasoning .

As a result I have been slow to update the AMO version unless the features I have been working on can be added back into it. Many of the changes I have recently been working on such as updated the profiles, updating the UI, Changing the implementation of the toggle based system, adding a context menu  for quick access and so on have all been work that I can add back into the AMO version. 

When I finish version 0.9.5.2 I'm going to add what I can from that into a limited version for AMO. In the past I have simply removed the script injection capability for the AMO version as it is the cause of the rejection. If allowed I will try to add some script injection code into the AMO verison.

**Comment by tegru** [comment]
Thanks for your reply. Very good information. Keep up the good work.

**Comment by dillbyrne** [comment]
@tegru  no problem. Thanks
