### ISSUE TITLE
Locales

### ISSUE THREAD

**Issue by alct** [dillbyrne/random-agent-spoofer#195]
While working on #192 , I fixed the French locales #194 and had a good laugh doing so :)

We should stop providing locales that have not been reviewed by a human (native speaker of the given language).

Do you have any insights (from AMO maybe) about what locales are used / where do users connect from for downloading RAS?

Given that:

- there isn't that much content ;
- most of the content refers to technical jargon (browser APIs,...) ;
- we're providing mixed content (some strings aren't translated) ;
- some sentences such as the one in the help tab can't be translated simply by replacing words at the same position in the sentence (even with #194, this sentence is wrong in French for instance) ;

I'm wondering whether it wouldn't be better to drop localization as a whole (like many other addons do).

**Comment by dillbyrne** [comment]
From the AMO statistics English, Russian French and German are the most widely used languages with users in the thousands  but there are smaller groups of users of other languages such as Spanish, Chinese and Italian.

I know some parts wont translate over well due to structural differences but it should still be enough to get the general idea.

Some of the strings can't be translated as they are defined in the JSON file. When I eventually add support for custom profiles users can put their own strings in there.

The thing messing up the help tab strings is the html for links and emphasis. The addon sdk allows for positional arguments to use in translations but they must be text only, html will not work. 

Removing the <em> tags would make that sentence easier to translate for all languages.

I only added localization support in this release so I would like to keep it. Also I'm sure many users would appreciate being able to use it in their native language.

**Comment by dillbyrne** [comment]
After reconsidering your post I think there is a strong argument to be made
to remove support for locales. Mainly due to the fact that the majority of the words  are technical in nature.

Doing so would speed up releases, reduce the addon size and avoid any UI issues due to localization.

I will remove locale support soon, test the addon and then if there are no problems I'll release it.

**Comment by alct** [comment]
Do we try to get rid of it for 0.9.5.2?

**Comment by dillbyrne** [comment]
@alct Yes I'm removing it now. It makes sense due to your points made above and it will allow for faster releases.

**Comment by alct** [comment]
Great!

**Comment by dillbyrne** [comment]
I've removed the localization support and the locales. I'll test the current version during the next few days when I get a chance and then release 0.9.5.2

**Comment by alct** [comment]
Good job!
