### ISSUE TITLE
[Feature Request] Add option to use Mozilla's geolocation service

### ISSUE THREAD

**Issue by Mosrite** [dillbyrne/random-agent-spoofer#201]
Hey,

I think it would be cool if RAS would feature an option to use Mozilla's geolocation service instead of Google's. To achieve this, the about:config entry "geo.wifi.uri" has to be changed to "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%".
Admittedly, this doesn't work very well at the moment as it is still in an early stage. But maybe, some people already want to use it? Or, they should at least know, that otherwise data is sent to Google.
Maybe, there could be added further options, e.g. OpenBMap's ("http://www.radiocells.org/geolocation/geolocate") or OpenWLANMap's (?) service as well?

Thanks for considering my suggestion!

**Comment by dillbyrne** [comment]
Helllo @Mosrite . Good Idea I'll add it in when I get a chance.

**Comment by dillbyrne** [comment]
@Mosrite I'll try to have this in the upcoming release 0.9.5.4.  I tried the mozilla location service and that worked fine but the openBmap one did not, did it work for you ?.

I found `http://www.openwlanmap.org/geolocation.cgi` for openWLANMap but that didn't work either. 

I'll see what else I can find before implementing it

Thanks for the suggestion I'm sure many of the users will appreciate a privacy respecting alternative to google's location services.

**Comment by Mosrite** [comment]
Thanks, great to see this being implemented! If I remember correctly I couldn't get OpenBMap and OpeWLANMap to work either. But honestly, integrating them would basically be just proof-of-concept, but would not add any real value (apart from being real FOSS), because these services are not good enough for everyday usage (at least that's my experience from using on them on my mobile).

**Comment by dillbyrne** [comment]
@Mosrite I have added the option in with the existing geo location preference.
 the checkbox will continue to toggle `geo.enabled` and the dropdown will handle `geo.wifi.uri`

![geo](https://cloud.githubusercontent.com/assets/2903711/8460089/9723dc52-2019-11e5-8be3-26729beec468.png)

Since users could set `geo.wifi.uri ` to anything, On install or upgrade I change it to mozilla if it is not already mozilla or google, as it needs to be one or the other to set the  UI based on the chosen preference. Either way it will have no effect unless the user has given a site permission to use their location and they have location enabled.
