### ISSUE TITLE
 Protect window.name doesn't work?

### ISSUE THREAD

**Issue by tegru** [dillbyrne/random-agent-spoofer#210]
ip-check.info reports Value "window.name" as traceable even though this option is selected in RAS.

**Comment by dillbyrne** [comment]
It is working fine here for me as you can see in the screenshot below.
 
![winname](https://cloud.githubusercontent.com/assets/2903711/7503669/6bc62d20-f43c-11e4-96ca-614f16f10aa1.png)

Can you make a new profile to test it https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by tegru** [comment]
I get the same results even with the new profile:

![screenshot - 05072015 - 12 44 23 pm](https://cloud.githubusercontent.com/assets/11595797/7512736/8247b7a0-f49e-11e4-86dd-3a39aaac7666.png)

**Comment by dillbyrne** [comment]
@tegru in that image the RAS tabs are grey which means the real profile is in use. Script injection is not enabled for the real profile.  It should work as expected when you are using a spoofed profile

**Comment by tegru** [comment]
Screenshot after enabling the standard options so they seem to work:

![screenshot - 05072015 - 01 02 42 pm](https://cloud.githubusercontent.com/assets/11595797/7512970/4316d708-f4a0-11e4-97dd-7fb14287cdf5.png)

**Comment by dillbyrne** [comment]
script injection options, the whitelist tab  and accept headers are disabled when the real profile is in use. The standard options and non accept headers  work when any profile is in use.

**Comment by tegru** [comment]
Ah, well sorry but that's just confusing and wrong IMHO... Why should I spoof my user agent in order to take advantage of the script injection options?

Also, it makes for example impossible to use these features with Tor Browser while using it's recommended user agent.

**Comment by dillbyrne** [comment]
I intend to make script injection features available with the real profile in the future. There was an issue with whitelisting while the real profile was in use and I needed to get 0.9.5.2 released in time for firefox 38 in case there was any issues with mozilla mandatory extension signing so that users will have an upto date version on AMO. 

It was simpler to temporarily disable script injection as that governs whitelisting until I can find the issue and address it properly.

As for the accept headers they are naturally not spoofed when the default profile is in use.
I'm fully aware it is not ideal and I intend to address it in a future update.

**Comment by dillbyrne** [comment]
I'll address it in #212 I'm closing this issue and the other one now

**Comment by tegru** [comment]
Well, maybe RAS shouldn't be so centered around user agent spoofing anyways... especially since user agent spoofing is controversial from anonymity point of view, AFAIK.

RAS has tonnes of other great features and user agent spoofing should be (is) just one of them... Maybe even the name should be changed...
