### ISSUE TITLE
Add setting for disabling the upcoming Pocket integration

### ISSUE THREAD

**Issue by dkasak** [dillbyrne/random-agent-spoofer#217]
The new Firefox nightly comes with integration to the [proprietary service Pocket](https://blog.mozilla.org/futurereleases/2015/05/13/get-a-firefox-account-and-test-new-features-in-firefox-beta/). I'm guessing you'll want to add an option for disabling this so I'm creating the issue to track it. Apparently there will be an about:config setting for this (`browser.pocket.enabled`).

**Comment by RoxKilly** [comment]
@dkasak Thanks for the link, that is interesting. Why do you think Random Agent Spoofer should have an option for disabling this feature?

**Comment by dkasak** [comment]
Well, it is in line with other bloat-disabling features of RAS (e.g. options for disabling canvas, webRTC, etc) since it is a potential privacy leak (and proprietary at that) with no user-friendly UI to disable it.

**Comment by RoxKilly** [comment]
@dkasak I get what you're saying; I have a different opinion. I don't think RAS should disable things simply because they bloat the browser. Otherwise, RAS itself will become too bloated and its options too overwhelming. If RAS starts trying to make the browser more lean, RAS will lose its focus as a privacy add-on.
As for the privacy part, I honestly don't know enough about Pocket to determine whether it is susceptible to privacy leaks, but from the link you provided I think it is opt-in (meaning a user has to create an account to use the service), so the average Firefox user would not be exposed. Do you have any more details about how it is a privacy leak?  Sorry if I missed something.

**Comment by alct** [comment]
+1 @RoxKilly

It should be integrated into RAS only if it actually leaks info (without requiring deliberate actions from the user) or can be used to fingerprint the browser.

@dkasak: can you please check for it?

**Comment by dillbyrne** [comment]
I have to look into this . I agree about avoiding bloat so It will depend on mozilla's implementation, which should require the user to opt in.

**Comment by dkasak** [comment]
I don't have any more information, but I'll keep an eye on this and try to investigate further.

**Comment by alct** [comment]
For the record: https://bugzilla.mozilla.org/show_bug.cgi?id=1172126

**Comment by dillbyrne** [comment]
Hi all

I feel that this issue should be addressed by mozilla themselves. I like the rest of you don't want proprietary services baked into the browser but I don't think RAS is the place to address this issue particularly. If it can indeed be completely disabled then the [user.js file](http://kb.mozillazine.org/User.js_file) would be the best way to disable it .

If not I can make a separate addon to block all requests to the pocket site as well as set the relevant about config entries.  

I'm inclined to close this issue now but I'd be interested to hear if anyone has anything more to add before doing so. I really appreciate the research on the issue you all have done and your input, It helps a lot. Thanks

**Comment by dkasak** [comment]
@dillbyrne, I agree, particularly since it seems (from further research) that the setting does nothing special (it just removes the button from the toolbar) and the code is only used when interacting with the button.

**Comment by dillbyrne** [comment]
@dkasak good to hear thanks
