### ISSUE TITLE
no whitelist tab

### ISSUE THREAD

**Issue by call5** [dillbyrne/random-agent-spoofer#227]
hello, i install the latest random-agent-spoofer in firefox 38.0.1 but i don't have a whitelist tab; here is the screenshot for more details 

![ras](https://i.imgur.com/hereTky.png)

**Comment by dillbyrne** [comment]
hello @call5 that is the old version. There is a new version awaiting review on addons.mozilla.org (0.9.5.2). In general though the AMO versions  are limited and some of the functionality such as script injection and the whitelist are  not supported in that version.

This is because the script injection is used for whitelisting and mozilla will not allow a version that messes with the date and time.

If you want a version with the script injection and whitelist you will have to uninstall the AMO version and install the github version at https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.3

**Comment by call5** [comment]
ok thanks for you speedy answers :+1:
