### ISSUE TITLE
Excluding browsers

### ISSUE THREAD

**Issue by paulderdash** [dillbyrne/random-agent-spoofer#231]
Using 0.9.5.3 set to Random (desktop) - Windows browsers - random interval. I sometimes get the message 'this browser is no longer supported' and then want to exclude those profiles in the list. However, if I tick those profiles it doesn't seem to 'remember' these after a restart?

**Comment by dillbyrne** [comment]
Hello @paulderdash . It is working fine here. I exclude the profiles and they remain excluded upon restart.

They are added and subtracted from the "extensions.agentSpoof.excludeList" preference when I tick and untick an exclude box.

Are the boxes still showing as ticked ?

**Comment by paulderdash** [comment]
If I select 'Random Windows Browsers', and exclude (tick) the first Chrome browser on the list, and restart FF, the profile is still there, now unticked. I wonder what it could be?

**Comment by dillbyrne** [comment]
@paulderdash I can see no reason as to why that is happening. What does the `about:config` preference `extensions.agentSpoof.excludeList` show when you tick the box. it should have that profile's id ( in this case `W1` ) added to it.

What value is that preference after ticking the box and after restarting ?. It should show a list of comma separated profile ids that you have selected for exclusion

Also can you try it in a fresh profile to see if it is something in your current profile that could be causing it https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by paulderdash** [comment]
OK - I did not look in about:config ... I see that preference now contains abU,abV,W3,W3,W72,W71,W70,W7,W6,W5,W4,W3,W2,W1,W1,W1,W1,W2 (some duplicates probably due to repeated attempts). But these profiles still appear in the list, unticked, after a restart. I have several profiles. I'll try another one.

**Comment by dillbyrne** [comment]
Ok  profiles like `abU,abV` are from a really old version. Did you update from an AMO version  to the github version (which is not supported ) ?. Duplicates should not be possible so it seems something is broken with your install.

You could try setting `extensions.agentSpoof.excludeList` as blank and close and restart the browser and then exclude a profile and close and restart and see if it shows up as ticked?   Note this will replace your current exclude list

Did you try a fresh profile like I mentioned above ?

**Comment by paulderdash** [comment]
I just tried in another (clean) profile and it works! 
Yes I did update fom the AMO version to the github 0.9.5.3 version. Should I not be using the github version i.e. should I go back to the AMO version?
Else if I continue with the github version I will do as you suggest. Alternatively I could remeove the add-on completely, restart the browser and do a clean install?

**Comment by dillbyrne** [comment]
Yes a clean install would be for the best. Sorry the fault is mine for not prominently displaying not to update from the AMO version to the github version. The reason for the problem is that they both advance at different rates and the update code for both versions has to take different things into account.

Sorry for the inconvenience caused. 

You can use whatever version you like AMO or github they just can't be mixed. So if you want to use the AMO version stick to that, if you want to use the github version then only use that. Switching from one to the other requires a removal of the old one and a fresh install of the  new one. From then on you can upgrade on your version of choice.

The only exception to the above will be the github version with 0.9.5.4 when the manifest id will have to be changed to avoid conflicts with the AMO signed version. Requiring all github version users to do a fresh install. This cannot be avoided unfortunately.

**Comment by paulderdash** [comment]
No need to apologise, it IS clearly stated - the fault is mine! Have done a clean install with the github version (prefer the interface), and it is working as expected. Will go to the AMO version when 0.9.5.+ comes through. Thanks for a great add-on.

**Comment by dillbyrne** [comment]
No problem. just remember to do a clean install when going back to the AMO version.
