### ISSUE TITLE
RAS Toolbar Icon Gone after Upgrade to FF 38.0.5

### ISSUE THREAD

**Issue by rmcohen3** [dillbyrne/random-agent-spoofer#234]
Hi,

RAS 0.9.5.3 is still installed, but the icon has disappeared from the toolbar, so I cannot access the majority of the settings (context-sensitive menu is still there). I tried removing and reinstalling RAS, but to no avail. Please assist.

Thanks,
Robert

**Comment by dillbyrne** [comment]
Hello @rmcohen3 I have tried 0.9.5.3 on a fresh version of firefox 38.0.5 (linux 64 bit). The icons shows up as expected as you can see in the image below
![pl-2](https://cloud.githubusercontent.com/assets/2903711/7984520/ee224402-0ac1-11e5-98c6-5f34c1a361a1.png)

So everything worked as expected on 38.0.1 and with 0.9.5.3 installed and once you updated to 38.0.5 it disappeared ?

What OS version are you using ? . Can you try it in a [new temporary profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and tell me if that works as expected.

**Comment by rmcohen3** [comment]
Hi dillbyrne,

Thanks for the quick response. Yes, everything worked as expected on 38.0.1 with 0.9.5.3 installed and once I updated to 38.0.5, the RAS icon disappeared from the toolbar. I am running Win7-64bit. I took your advice and created a new "Test" profile. It resulted in a new vanilla browser. I used it to re-install RAS. The icon appeared on the toolbar. I looked at the RAS settings and they were back to default. I then opened FF with my original default profile. The RAS icon was back on the toolbar. I looked at the RAS settings and they were back to default. I then closed both browser instances, deleted the Test profile, and re-opened my default profile. The RAS icon still appeared on the toolbar, but again, the setting were back to default. So, thank you for the workaround. But, is there any way to recover the RAS settings, as well as back them up so that I avoid this problem in the future?

Thanks,
Robert

**Comment by dillbyrne** [comment]
Hi @rmcohen3  

It actually wasn't supposed to be a work around . I was trying to determine if the problem was limited to your profile. It should not have happened in the first place . I can only guess it was your profile that became corrupted. I have not been able to reproduce it

It could be something with firefox itself during the update.

You could backup your profile to back up all of your firefox settings but there is no option in RAS specifically to back up its settings.

Has it been working properly since ?

**Comment by rmcohen3** [comment]
Hi dillbyrne,

Thanks for following up. Unfortunately, the icon seems to come and go. I can't see any rhyme or reason to it. I tried all day yesterday to bring it back and had no luck. I was tempted to refresh FF, but rebuilding it the way I like it is very time consuming so I didn't go through with it. I tried playing with test profiles again today and it came back. It is very frustrating. I love RAS and now consider it a mandatory add-on to my browser. I'm surprised no one else has had problems, although, I do understand that with all the add-ons out there, everyone's browsers become rather unique. I run a bunch myself, and also run FF inside a sandbox, so teasing problems out can be really complex.

Thanks again,
Robert

Date: Fri, 12 Jun 2015 03:56:29 -0700

**Comment by dillbyrne** [comment]
I would recommend to switch to a new profile and keep the old one around just in case. When using the new profile install your addons one by one and use it for a bit after each one and see if you can notice anything. This will tell us if it is an addon causing it or if it the profile became corrupted.

What addons are you using with it ?

**Comment by rmcohen3** [comment]
Haha, easier said than done :) It's a wonder that everything has been working well until now. I am using the following addons:

about:addons memory
BetterPrivacy
Cache Status
Calomel SSL Validation
Classic Theme Restorer
Empty Cache Button
Ghostery
Gmail Notifier
Hotmail Watcher
HTTPS Finder
HTTPS-Everywhere
Lazarus: Form Recovery
NoScript
OpenWith
Random Agent Spoofer
RefControl
RequestPolicy
RequestPolicy Sync
Self-Destructing Cookies
SSleuth
Status-4-Evar
StopTube
TrafficLight
uBlock Origin
Virus Total Scan Url
WOT
Xmarks
YouTube High Definition

Thanks,
Robert

Date: Fri, 19 Jun 2015 07:53:13 -0700

**Comment by akwala** [comment]
I saw similar behaviour with FX 38 in one of my profiles. I started with all addons disabled and enabled them in small groups. When I came upon the group that, when enabled, resulted in the icon's disappearance, I found that the icon didn't return even after disabling all the addons in that group. However, at some point everything in the navigation bar (location bar, "hamburger" icon, etc.) also disappeared and the Customize tab was also completely empty. Disabling Classic Theme Restorer (CTR), then re-enabling it returned the nav bar and the Customize tab to normal (including the RAS icon) except the "hamburger" icon was now on the Customize tab and had to be dragged to the nav bar. When the nav bar disappeared again (not sure what triggered it) I was able to get it back the same way. My guess is that there is an obscure issue with CTR that occurs in FX 38 and/or when CTR and one of my other addons are both enabled -- I gave up since I was able to get things back to normal; the browser could use a debugging/troubleshooting component for users to help identify such incompatibilities.

**Comment by dillbyrne** [comment]
Hi @akwala Thanks for the information :+1: , that sure sounds like it could be the issue. When I get a chance I'll see if I can replicate it with CTR and RAS and upgrade from 38 to 38.0.5

**Comment by UnoPx** [comment]
Hello, I am having a same issue after updating my Cyberfox x86_64 (AMD) from 38 to 40. 
I have tried to enable/disable - restart browser, also tried to uninstall and re-install to no avail.
Seems like RAS is working but the toggle icon is completely gone.

Here is a list of my Add-Ons:
HTTPS-Everywhere 5.0.7
NoScript 2.6.9.34
Policeman 0.18.1.1
Random Agent Spoofer 0.9.3.1.1
uBlock Orgin 1.0.0.1
Ghostery 5.4.6
 
Any help would be appreciated. Thank you so much for your hard work on this Add-On <3

**Comment by actionpapst** [comment]
Same here. Icon disappeared with FF38 I guess. Now I'm on FF40 and cannot use the addon the way I'd like to. Can't activate the addon at all actually. Tried a fresh profile as well as a new installation. Arch x64.

**Comment by rmcohen3** [comment]
I can't confirm or deny whether this has truly made the difference, but ever since I moved the RAS icon away from the end of the toolbar, it hasn't disappeared again (knock on wood). I used to place it on the far right hand side. It is now the second icon over from the address bar.

**Comment by dillbyrne** [comment]
Hello @actionpapst  see #277 

@rmcohen3 That is interesting. I still have to check out CTR and RAS and see if that causes the issue. I'll try to get it done soon.

**Comment by actionpapst** [comment]
Thanks. Newest release did the trick.
