### ISSUE TITLE
RAS Toggles geo.enabled To True When Spoofing On/Off

### ISSUE THREAD

**Issue by xahujyu** [dillbyrne/random-agent-spoofer#236]
Using openSuSE 13.2 Firefox 38.05. Clicking RAS spoofing on/off causes geo.enabled to true state irregardless of previous state. Also when RAS disabled. Hope this helps.

**Comment by dillbyrne** [comment]
Hello @xahujyu  What version of RAS are you using ?

If it is 0.9.3.1  from the mozilla addons site it is because RAS restored the state of options to a working state to ensure compatibility when you disabled it.

The behaviour has been removed in later versions because it confused users . Later versions do not have a toggle system and options must be toggled on or off by the user.

**Comment by xahujyu** [comment]
It is 0.9.3.1. And my version of Firefox is 38.0.1 and not 38.0.5. I'll wait for the update through SuSE Yast. Thanks for the info, and a great addon.

**Comment by dillbyrne** [comment]
No problem and thank you. You could  be waiting a while due to mozilla taking weeks to approve addons. If you would prefer to use the github version instead which is more up to date and updated much more frequently you can do so by uninstalling the current version and then clicking the xpi link at https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.3
