### ISSUE TITLE
How to use whlitelist rules for websites

### ISSUE THREAD

**Issue by potholiday** [dillbyrne/random-agent-spoofer#237]
I have the latest RAS 0.9.5.3 and  I uses it to spoof my browser (random desktop). I want to prevent RAS from running in some particular websites like gmail.com, facebook.com, tumblr.com, cnet.com , youtube.com etc while running a Random Desktop profile . In RAS itself there is a whitelist tab which i enabled.  I want to know how we can add above websites to the whitelist rules. current default rule is
`[{"url":"play.google.com"},{"url":"s.ytimg.com","options":["canvas"]},{"url":"youtube.com","options":["canvas"]}]`

**Comment by ProgrammerZeta** [comment]
Inside the [] you have a list of {} sections separated by commas. You simply add a new {} section for each site you want to whitelist. And don't forget the comma. 

A tip could be to copy the whitelist "text" to a text document and use notepad to edit it. Then copy it to the RAS whitelist. Next time you bring up the whitelist in RAS you'll see that the formatting(linebreaks) and the order has changed, so that's why it can be easier to use notepad.

Here's an easier to read example you can use where I've added facebook.com and disabled all available options in RAS. If you don't want to disable any options, simply remove all quoted strings inside the brackets of "options":[]

[
{"url":"facebook.com","options":["referer","xff","via","ifnonematch","windowName","canvas","screen","date"]}
,
{"url":"play.google.com"}
,
{"url":"s.ytimg.com","options":["canvas"]}
,
{"url":"youtube.com","options":["canvas"]}
]

It'll be easier to understand if you have a notepad window with a width so it shows only one line per row. Example:
[
{"url":"facebook.com","options":[]}
,
{"url":"play.google.com"}
,
{"url":"s.ytimg.com","options":["canvas"]}
,
{"url":"youtube.com","options":["canvas"]}
]

**Comment by potholiday** [comment]
@ProgrammerZeta Thanks for the quick reply. But can you explain a lit bit more about the format and syntax used for entering website names in the whitlelist. Lets say if i want to disable RAS in these website google.com, facebook.com, github.com, cnet.com, twitter.com. whether this format will work

[
{"url":"google.com"}
,
{"url":"facebook.com"}
,
{"url":"github.com"}
,
{"url":"cnet.com"}
,
{"url":"twitter.com"}
]

can you describe a more about your code {"url":"facebook.com","options":[]}  what is  options

**Comment by ProgrammerZeta** [comment]
That looks ok. But you should make sure you understand what the whitelist actually does. It does not fully disable RAS.

When used as in your example (without any options specified) it will use the whitelisted user agent information meaning it will appear to these sites as your using the whitelisted browser and OS instead of a random or manually selected profile. Personally I see little point in using the whitelist that way. I think the great advantage with the whitelist are the options. Or as stated in the Whitelist manual: "The whitelist is supposed to be used for problematic sites"

Options
If you have enabled some of the options in the Headers tab or in the Options tab under Script Injection, you have the possibility through whitelist options to undo these settings for a specific site. A good example are the pre-defined youtube.com and s.ytimg.com that has canvas specified. That's because you can't watch Youtube videos if canvas support is disabled in RAS. Without that canvas option for those sites you'd have to uncheck "Disable Canvas support" to watch videos, and then remember to check it again after.
But if you haven't selected any script injection options or some of the options in the Header tab, then there's no need in specifying any options for a whitelisted site. I hope that explains it, but to make it even more clear I gave an example in my first reply to show what an option look like if you specify all of them that are supported in the current RAS version:

"options":["referer","xff","via","ifnonematch","windowName","canvas","screen","date"]

In the Whitelist Usage manual these are explained more under the heading "Header Options" and "Javascript Options".

And yes, {"url":"facebook.com","options":[]} is the same as your example, because there aren't any options specified inside the []

https://github.com/dillbyrne/random-agent-spoofer/wiki/Whitelist-Usage

**Comment by potholiday** [comment]
Much of my doubt get clarified so options are important in white list. 

Lets say while visiting facebook i want RAS to disable spoofed pc time and browser profile (original firefox after spoofing chrome,opera etc)

so how do we do it

{"url":"facebook.com","options":[date,?]}

**Comment by dillbyrne** [comment]
Hello @potholiday Sorry about the delay in getting back to you. Thanks @ProgrammerZeta for providing assistance.

for your query above you would use `{"url":"facebook.com","options":[date]}`

if you just want to spoof the profile with no options you can omit the options so you can have `{"url":"facebook.com"}`

**Comment by ProgrammerZeta** [comment]
I think there's still some confusion as @potholiday mentioned "original firefox". The whitelist profile is not necessarily your real profile. The predefined whitelist profile in current RAS is Firefox 37 (en) Win 8 (32). That is unless you change it yourself. The whitelist profile is made up of 11 different settings/strings so it's not as simple to change as many other RAS settings. 
I guess you can use the whitelist profile in three ways: 
- use the predefined RAS whitelist profile
- modify it to match the settings of your real profile
- modify it to whatever spoofed values you want

But you should also note that if say you have a Win 8 64-bit PC but your whitelist profile says 32-bit, that could mean you're offered 32-bit instead of 64-bit programs if you try to download any programs from a whitelisted site. The easiest way to avoid this is to switch to the Real Profile before downloading any software.

@dillbyrne My pleasure! Thank YOU for this truly great extension :)

**Comment by dillbyrne** [comment]
@potholiday well spotted :+1: .  Thanks , It has a long way to go still but it is getting there slowly.

**Comment by potholiday** [comment]
@ProgrammerZeta   Your are right  I am new to RAS and I am a bit confused about its usage. The main problem was when i open `addon.mozilla.org` page to install some `extension` ; if RAS is enabled (as a chrome, opera etc spoofed profile) firefox will not  allow addons to be added to the browser. But yours and @dillbyrne  explanation solve my main problems. Once more thanks to both you for your kind explanation
