### ISSUE TITLE
Signed FF addon?

### ISSUE THREAD

**Issue by SoHiggo** [dillbyrne/random-agent-spoofer#247]
Hi there.

Excuse the noob question, but I checked this:

https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/?src=search

It does not seem to reflect latest version in /releases/ section of this repo.

Is there something I am missing here?

I installed the XPI from releases to test, but it is not on the official FF site, so I distrusted it and uninstalled. I reviewed the source and did not like a few lines of code because they are too privileged. Can we get FF addon team to review please?

**Comment by SoHiggo** [comment]
For clarification, I did not trust this part:

(found in the compiled XPI)

![__](https://cloud.githubusercontent.com/assets/6738367/8387068/af287a12-1c4d-11e5-993f-45a719138447.jpg)

I know this is FOSS and a plugin like this is unlikely to backdoor a browsing session, but I must prevail.

**Comment by dillbyrne** [comment]
Hi @SoHiggo 

It is good that you are cautious :+1:  we need more eyes on projects.

To try to assuage you concerns

I have a version of RAS at 0.9.5.2 on AMO that has been in the review queue for a month.
![ras](https://cloud.githubusercontent.com/assets/2903711/8396639/9c13ccec-1da6-11e5-88fd-1761d3944132.png)

This version has the same code as the github version except script injection has been disabled as AMO reviewers will not allow me to spoof the screen and date as they have said it could break sites for users. the exact code used for the AMO version can be seen in the [AMO-Limited](https://github.com/dillbyrne/random-agent-spoofer/tree/AMO-limited) branch of this repository.


As to the page mode code, that is using a the [page mod](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod) module of the addon API

Inject simply refers to the name of the [injection script](https://github.com/dillbyrne/random-agent-spoofer/blob/AMO-limited/data/js/inject.js) that we use to inject spoofed JavaScript values into sites that we cannot spoof using built in prefs and or to supplement the builf in prefs.

I will be submitting the github version for signing by Mozilla once they open up the signing process to externally hosted addons. See #228 


As for not reflecting the latest changes, this is partially due to the fact that for a large time most of the development was taking place on the script injection and the whitelist which depended on it so I waited until I had a significant change that would apply to core areas before I submitted the update to the AMO version .

If you have any more questions feel free to ask.

I'm going to close this now as the other issue deals with signing.

**Comment by SoHiggo** [comment]
Great thanks for clarifying. I was just uncertain about that part. This is looking a lot more reputable now :)

**Comment by dillbyrne** [comment]
No problem.

**Comment by SoHiggo** [comment]
BTW: Be careful with whitelists:

Sometimes it is possible for domains to be 'hihacked' by the bad guys

See:

http://thehackerblog.com/the-noscript-misnomer-why-should-i-trust-vjs-zendcdn-net/
