### ISSUE TITLE
[bugs and problems]

### ISSUE THREAD

**Issue by s00iyool** [dillbyrne/random-agent-spoofer#248]
1. Add an option to disable notification(right below - UA change alert). Very annoying.
2. "Set Referrer to": add "same as URL" and "home base".

same as URL ... request = referrer
home ...
request = https://github.com/dillbyrne/random-agent-spoofer/issues/new
referer = https://github.com/

3. Whitelist doesn't disable Referrer spoofing.
My whitelist:
[{"url":"john.xxxx.org"}]

I'm expecting john.xxxx.org's referrer is default, but RAS block all of referrer.
(Referer set is "None", but RAS must respect whitelist.

john<--->john Referrer OK
john<--->outside Referrer CHANGE
outside<--->john Referrer CHANGE

"Normal. But block 3rd party".)

4. Please try out these 2 add-ons. Please improve like them.
https://www.dephormation.org.uk/?page=81
http://www.stardrifter.org/refcontrol/

**Comment by dillbyrne** [comment]
For notifications see:  https://github.com/dillbyrne/random-agent-spoofer/issues/241#issuecomment-113533888

There is already an issue open for improving the referer support like you suggested #110  
https://github.com/dillbyrne/random-agent-spoofer/issues/110.

The whitelist is to allow the referer where it has been blocked otherwise.

So if you have selected to not send the referer to site but want to send it to `example.org` then `{"url":"example.org","options":["referer"]}` will allow it

see https://github.com/dillbyrne/random-agent-spoofer/wiki/Whitelist-Usage
