### ISSUE TITLE
Why different features on github version?

### ISSUE THREAD

**Issue by Noitidart** [dillbyrne/random-agent-spoofer#250]
I was wonderng how com you dont put the features of github version onto AMO version, installing addon from github is very difficult.

**Comment by dillbyrne** [comment]
Hello @Noitidart . AMO will not allow me to spoof screen and date/time values as they said it could break some sites for users. 

The AMO version has the same code as the github version except script injection has been disabled as AMO reviewers will not allow me to spoof the screen and date as they have said it could break sites for users. The exact code used for the AMO version can be seen in the [AMO-Limited](https://github.com/dillbyrne/random-agent-spoofer/tree/AMO-limited) branch of this repository.

I will be submitting the github version for signing once the process is opened to externally hosted addons.

**Comment by Noitidart** [comment]
Thanks very much for your detailed reply!

Is there any chance you could make those features an option, with default being off, (and when they enable it, maybe a small warning that some sites may break?) then maybe reivewers will except it? That way we can all get to use the wonderfullness that is this addon! :)

**Comment by dillbyrne** [comment]
I have made the features optional since 0.9.5.2 where users can click to enable / disable script injection completely.  In the current AMO version in the review queue the script injection has been completely disabled so it will pass review. I have however asked the reviewer if he/she would look at the script injection code as it is now and see if there is anything I can improve upon to get it back into AMO. 

I'm still waiting for it to be reviewed but I will update when I know more.

**Comment by Noitidart** [comment]
Thank you very much please please try to get github version onto AMO I really love AMO it's so easy and simple. I got some people I know on the reviewing team so if you need help let me know :)

**Comment by dillbyrne** [comment]
Thanks I appreciate it. I'll see what they say first and let you know. I'd prefer to have a single version again myself.

**Comment by dillbyrne** [comment]
@Noitidart :+1: Thanks for your help in the 0.9.5.5 review process. I really appreciate it!

**Comment by Noitidart** [comment]
;)
