### ISSUE TITLE
Build from latest source

### ISSUE THREAD

**Issue by 00fsas** [dillbyrne/random-agent-spoofer#254]
I didn't understand the steps you provided to build the xpi from the latest source is there a tool that simplifies all the work or could you elaborate?

Thanks

**Comment by dillbyrne** [comment]
Pulling from master is not recommended due to frequent changes and there could be bugs. That said you have to use jpm instead of cfx as mozill changed to a new tool. I'll update the documentation now . https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm



if you want an up to date github version then use https://github.com/dillbyrne/random-agent-spoofer/releases/download/0.9.5.3/random-agent-spoofer.xpi

is there a specific step you ahve having trouble with ?

**Comment by 00fsas** [comment]
Yay! I got it working now. Previously when using cfx I would get errors and I knew I did it right. It makes sense as cfx is no longer supported. Thank you again.

**Comment by dillbyrne** [comment]
Glad you got it working. I'm sorry for the inconvenience. I forgot to update the instructions during the switch.
