### ISSUE TITLE
Why not just pass through user agent string?

### ISSUE THREAD

**Issue by cattledogit** [dillbyrne/random-agent-spoofer#258]
The most common user agent string for a given browser must certainly be the current version of that browser, rather than one among ras's list of recent versions of that browser (even though Panopticlick's User Agent's "one in x browsers" may not reflect that immediately).

Maintaining user agent strings must be time-consuming. Delivering the browser's actual string, or even pulling the string from an automated list of the latest versions of each browser, would eliminate this task.

**Comment by RoxKilly** [comment]
In my opinion, just delivering my actual User Agent would make me more easily trackable. Even with real, up to date UA string, the Panopticlick's analysis would likely show "one in x browsers" with a large x value, meaning if the sample of users that a site tracks is not huge, my UA will be instantly recognizable, or at best one of a small set of matching UAs.

For those reasons I think spoofing is the right way to go. your idea of pulling the string from an automated list of the latest versions of each browser sounds good, but I don't know enough to know whether it's doable. The UA string is not limited to browser information; it also contains info about the OS environment, so the same browser with the same version could have many different UA strings.

I do think you're unto something though. If there is a resource that publishes an auto-updated list of the most common user agents along with their OS, UA spoofing software such as RAS could make use of it.  A popular website such as Wikipedia or Facebook or Google would be perfectly place to publish such a list, because they see a lot of UAs all day.  Users of the site (or whomever those UA strings are taken from) may not like that though.

**Comment by cattledogit** [comment]
@RoxKilly wrote:
> ... Even with real, up to date UA string, the Panopticlick's analysis would likely show "one in x browsers" with a large x value

That's correct. However, Panopticlick's counts are based on the fingerprint of each of their ~6M visitors at the time of their last visit, not those ~6M visitors' browser fingerprints as of today.

Today Panopticlick reports my user agent "Windows NT 6.3; WOW64; rv:39.0" (latest FF on Win 8.1 64-bit) as "one in 3429 browsers have this value". However, the majority of FF users likely have the latest FF version, so the 3,429 would be much lower if Panopticlick was able to check the current user agent strings for those ~6M browsers today.

**Comment by dillbyrne** [comment]
It would not work because we do not only maintain a single string for a profile but lots more and what constitutes a profile could still grow . See https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json 

Not only that but things can change from version to version like new headers added or changes in screen sizes when a newer model of a phone comes out.  

The best way to do it is to have users help maintain it and issue new releases frequently. As I have been aiming to do . This release has been held up by Mozilla's new signing policy. I'm still waiting to hear more from them about signing for externally hosted addons.

Note the [Agent](https://en.wikipedia.org/wiki/User_agent) in Random Agent Spoofer does not refer to the user agent string but to the browser acting as an agent on the user's behalf. So we aim to randomly spoof the browser which is not the same as randomly spoofing a string.

There are lots of addons that simply spoof the user agent string but they are easy to spot and in many cases make you stand out more due to inconsistencies. It is  more effort to maintain RAS profiles I agree, but it is because of all the extra effort that makes RAS what it is.

**Comment by cattledogit** [comment]
> Not only that but things can change from version to version like new headers added or changes in screen sizes when a newer model of a phone comes out. 

Perhaps it would make sense to pass those new headers and the screen sizes through too. I've read that fingerprinting vendors have found fingerprinting to be useless on mobile devices because there are too many of each device.

"Browser Plugin Details" is always the most unique part of my fingerprint at Panopticlick. I'd feel reasonably anonymous if RAS allowed me to control just this part of the fingerprint.

Thanks for RAS!

**Comment by dillbyrne** [comment]
>Perhaps it would make sense to pass those new headers and the screen sizes through too. That is what is currently done. Which is why the profiles are maintained as they are.

The plugin related option in RAS is only a simple about config setting for now. I only prevents plugin enumeration but it would be still possible to figure out what plugins a user has installed. More work is needed on it for now we cover the most direct method.
