### ISSUE TITLE
Use document fonts?

### ISSUE THREAD

**Issue by gerroon** [dillbyrne/random-agent-spoofer#259]
Hi

This new option is a bit confusing , even for me after using the previous version.

Is this saying that use the fonts come with the page or is it saying use the standard document fonts?

thanks

**Comment by RoxKilly** [comment]
@gerroon I agree that the language of that option is confusing. I think of that option as  "Enable/disable fonts protection".  Below are the details:

Enabling `Use document fonts` in RAS will set the `browser.display.use_document_fonts` option (found in `about:config`) to value 0. As a result, the browser will NOT download or use web document fonts, but rely on its own font set.  Another effect is that the browser will no longer publicize the fonts installed on the machine. This setting enhances security because some font sets have been vectors for infection.  It also enhances privacy because websites will be unable to fingerprint the browser based on which fonts it exposes. [Browserleaks.com font detection](http://www.browserleaks.com/fonts) test should show "0 Fonts detected"

Disabling `Use document fonts` in RAS will set the `browser.display.use_document_fonts` options (found in `about:config`) to value 1. As a result the browser will download and use document fonts, and will allow websites to see the fonts installed.  This allows you to see websites as the designers intended, and allows you to see font-based icons (for instance, you will be able to see the icons for the different tabs along the right edge of github pages, and you will be able to see the GitHub brand icon at the top left corner of the page).

**Additional notes:** if you want the security of fonts protection, but do not like the browser's own standard font, you can adjust it using the steps below
1.  go to url `about:preferences#content`
2.  Click the `Advanced...` button
3.  Uncheck `Allow pages to choose their own fonts` (it will already be unchecked if you turned on fonts protection by enabling `Use document fonts` in RAS)
4.  Fiddle with the fonts and font size until you find ones that suit you. I've attached an image of my settings: they make most webpages pleasant enough to read for me
![1](https://cloud.githubusercontent.com/assets/12346501/8635502/f603da34-27f2-11e5-8ce7-051c929dc8aa.png)

**Comment by gerroon** [comment]
@RoxKilly 

Hey thanks for the detail info.


Btw there is also downloadable.fonts.enabled  however that does not seem to do anything in my view.

I personally do not five a flying raccoon to what designers want me to see, i care about my privacy.

The downloadable fonts are also a page performance hit. I do not understand why there are so many stupid web designers and programmers outthere who think these fotn downloads are a good option. Brains without minds

**Comment by RoxKilly** [comment]
I don't think designers are stupid; they use the tools at their disposal to try to make their product stand out from the competition and consistent with company branding.  You can imagine for instance a company that offers Pirate-themed amusement parks.  It will want all its messaging to be pirate-flavored.  It will want to present itself consistently in advertisements, mascots, park rides, park tickets, pamphlets, billboards etc.. and website.  Web fonts ensure that all users, no matter their OS or device, will view the company's messaging in a way that is consistent.

Web fonts that contain icon packs offer an additional advantage. Images tend to use a lot of space (bandwidth to transfer to the browser) and tend to look pixelated if you up-size them.  On the other hand, fonts look consistent at all sizes. So web fonts that include icons can be a good alternative to using actual images.

Unfortunately, as is the way with all technologies, new capabilities give birth to new vulnerabilities and there are always people looking to exploit the vulnerabilities. Like you, I am much more concerned about my privacy and security than about experiencing a site the way the designers intend, so I avoid web fonts but I don't think people who came up with them or who use them are brainless.

**Comment by gerroon** [comment]
Well they can design their web sites that uses fonts from their own servers instead of someone else's if tha tis the issue. 

The web has become so interdependent (which makes it fragile in a way) that one day it will crash for good

**Comment by dillbyrne** [comment]
@gerroon @RoxKilly Your right the working is confusing .  What do you feel about `Enable font protection` ?

**Comment by gerroon** [comment]
yeah that is fair in my view.  Or "disable downloadable fonts" ?

**Comment by dillbyrne** [comment]
The option does not disable downloadable fonts though. It limits the allowed fonts to three specific fonts. 

I'm going to change it to `limit detectable fonts` as I feel that explains it best and reduce the potential for confusion with regards to downloadable fonts which is a separate issue
