### ISSUE TITLE
Question: Do you use all these options?

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#260]
Hi,

So far this is the best addon I've seen for Firefox, really great work!

For the ```general.useragent.vendor```, I noticed that ```Google Inc``` was listed for ```MacIntel```, why is that?

I've always left the ```geo.wifi.uri``` empty.

```Set Referer to None```, but the Network.http.sendRefererHeader is shown as ```2``` and I always have used it on ```0```.

I've been playing for serveral years with Firefox security and fingerprinting, and below are other options I also use in the ```about:config``` that I noticed you do not have in RAS...

 ```
browser.cache.disk_cache_ssl
false

browser.cache.offline.enable
false

browser.safebrowsing.enabled
false

browser.safebrowsing.malware.enabled
false

browser.search.update
false

browser.sessionhistory.max_entries
2

browser.sessionstore.privacy_level
2

browser.urlbar.autocomplete.enabled 
false

browser.zoom.siteSpecific
false

clipboard.autocopy
false

dom.event.contextmenu.enabled
false

dom.indexedDB.enabled
false

dom.storage.default_quota
0

extensions.getAddons.cache.enabled
false

media.cache_size
0

network.dnsCacheEntries
100

network.dns.disableIPv6
true

network.http.keep-alive.timeout
20

network.http.sendSecureXSiteReferrer
false

network.websocket.enabled
false
```

**Comment by dillbyrne** [comment]
Hello @Geyup 

Thanks . I'm glad you like it

> For the general.useragent.vendor, I noticed that Google Inc was listed for MacIntel, why is that? 

The [profiles](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json) in RAS are taken from real browsers and devices. So that particular profile had google as the vendor but the platform was on MacIntel. Such as Chrome on Mac




					{
						"description":"Chrome 42.0.2311.152 (OS X 10_10_1)",
						"useragent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36",
						"appname":"Netscape",
						"appversion":"5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36",
						"platform":"MacIntel",
						"vendor":"Google Inc.",
						"vendorsub":"",
						"buildID":"",
						"oscpu":"",
						"accept_encoding":"gzip,deflate,sdch",
						"accept_default":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
						"accept_lang":{"en-US":"en-US,en;q=0.8"},
						"pixeldepth":"24",
						"colordepth":"24",
						"screens":"1280x800,1366x768,1440x900,1920x1080,2560x1440,2560x1600,2880x1800",
						"profileID":"M1"
					},


>I've always left the geo.wifi.uri empty. 

As have I but in the newer versions it defaults to mozillas location service if you have not set it to use googles instead. It is only used if geo.enabled is true and if you have explicitly allowed a site to use your location so having it set as something will do no harm

>Set Referer to None, but the Network.http.sendRefererHeader is shown as 2 and I always have used it on 0.

RAS uses a custom preference and [custom code](https://github.com/dillbyrne/random-agent-spoofer/blob/master/lib/Chrome.js#L116) to handle the referer header so we can selectively whitelist it. In the next release it will uses other built in referer preferences to fine tune it in addition to the custom preference.

>I've been playing for serveral years with Firefox security and fingerprinting, and below are other options I also use in the about:config that I noticed you do not have in RAS...

I'll look into them and see what would be best to add. As for what options RAS currectly uses you can see the preferences in the [PrefServ.js](https://github.com/dillbyrne/random-agent-spoofer/blob/master/lib/PrefServ.js) file.

**Comment by Geyup** [comment]
thank you and keep up good work

**Comment by Geyup** [comment]
By the way, here's what made me consider setting

browser.cache.frecency_experiment
-1

https://trac.torproject.org/projects/tor/ticket/13575

**Comment by dillbyrne** [comment]
@Geyup Thanks , looks like there has been no update on that issue since. It may be good to disable it by default if it causes no adverse effects on browsing.
