### ISSUE TITLE
Reimplement RAS toggle system

### ISSUE THREAD

**Issue by potholiday** [dillbyrne/random-agent-spoofer#272]
if we enabled RAS in some of the websites like youtube will not work properly especially the css and youtube player of the website with chrome/chromium(all OS's) user agent. Now when this problem occurs i manually toggles between the real and random (desktop) till non chrome/chomium User agent comes. I have tried to exclude chrome/chromium from all desktops but after a fresh restart it resets back to the previous option and I have to once more exclude chrome/chromium option manually.

If possible can you provide a toggling of user agent feature in the toolbar icon itself (when clicked on the icon) instead of selecting from the menu

**Comment by Robbendebiene** [comment]
I also noticed some problems with youtube and RAS. Sometimes it is working sometimes not, even if i disable the User-Agent spoofing and further other options. Missing images are: youtube logo, youtube thumbs, commentary like buttons..

**Comment by dillbyrne** [comment]
There is built in support for youtube in the whitelist, make sure it is enabled. It should play videos no problem once the whitelist has been enabled and as long as you didn't remove the youtube related entries. This works for images and playing video and viewing comments. I don't have a google account to test posting comments at this time. 


```
[

{"url":"s.ytimg.com","options":["canvas"]},      
{"url":"youtube.com","options":["canvas"]}

]
```

As to your question about toggling. I can't provide a toggle feature in the toolbar like old versions of RAS because the old widget code had to be removed and the new ActionButton API does not allow me to override right clicks and the left click is used to show the panel.

I removed the toggle ability so I could clean up lots of code and because it confused many users when RAS would change all the settings when they toggled it on or off (as they would reset to the firefox defaults, which is a known state). 

Due to the sheer number of emails I have been getting from github notifications about this I am going to add the toggle system back into RAS but this time it will require less code and make use of the code cleanups I was able to do after removing the old code.  

It will have to use the RAS context menu to select the change or select the real profile in the panel. I'll be more specific when it is done.

Right now the idea is to make it function like the old toggle system but the code will be quite different.  

This will mean that the real profile entry will disable everything, the profile spoofing, the headers, all extras including script injection options and the whitelist.

I can't guarantee it will be available in the next release 0.9.5.4 but if not it will be in 0.9.5.5

You can track it in this issue.


>after a fresh restart it

What specifically is a fresh restart ?

**Comment by RoxKilly** [comment]
@potholiday Disabling canvas support in RAS (from Options tab) breaks several websites. As @dillbyrne pointed out, you can add those sites to a whitelist to enable canvas just for them.  I have been uncomfortable with this solution because it allows the sites (many of which are Google properties such as YouTube and Gmail) to use canvas fingerprinting to track us.  So, how can we use canvas where necessary while preventing fingerprinting?

The [CanvasBlocker add-on](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/?src=api) is the answer.  It allows websites to use canvas to draw things on the page, but spoofs the fingerprints generated. 
1) uncheck "Disable canvas support" in RAS
2) Install CanvasBlocker and set block mode to  "Fake readout API"
3) Done!

I would really like to use RAS as the only spoofing tool but its canvas protection is too limiting.  Note that @dillbyrne has stated his intent to bring this functionality into RAS (#111)

**Comment by B00ze64** [comment]
> This will mean that the real profile entry will disable everything, the profile 
> spoofing, the headers, all extras including script injection options and 
> the whitelist.

@dillbyrne: Ah please, do not do this! Like other users, I use RAS for the additional options it has, I do not use Agent spoofing at all. If you make this change, I will have to stop using RAS, which is the only tool so far that I know if which can spoof ETags. This change is a disaster!

**Comment by dillbyrne** [comment]
@potholiday @RoxKilly  

I'm working on this now. Currently toggling the addon off will  store the relevant options in temporary settings and reset the preferences  and the real profile as selected 

If toggled on the settings are returned to what they were before toggling off and the previous profile is selected

@B00ze64  NOTE: if the addon is enabled and the real profile is selected it will not disable the other stuff. This will work how you want it. I will try to decouple as much stuff away from the real profile too as I can so script injection functions can be used with the real profile .

Toggling can be done in two places, the mouse menu or in about addons.

I have a lot more to do on this to get it fully working but I thought some may like an update

**Comment by B00ze64** [comment]
Woohoo! You know this addOn shouldn't be called RAS; it should be called Enhanced Privacy or something - it does so much more than just spoof the agent string :-) I will soon be able to use the WhiteList along with the real profile, nice! You'd be surprised how many websites are now using eTags and break when this is spoofed. I don't get it at all; why don't they let the browser ask for a timestamp and maintain the cache that way? To me eTags are not necessary. Unfortunately, a lot of websites just won't serve any resources (besides the base HTML file) if eTags are disabled, thereby needing to be whitelisted. Thanks!

**Comment by dillbyrne** [comment]
This is done now. I still have to test it to make sure all the necessary options are being toggled but the implementation itself is finished.


How it works

3 states 

1. (Red) Disabled: Everything is  disabled
2. (Blue) Spoofing: profile is spoofed + whatever else you have selected is applied  
3. (Grey) Real: profile is not spoofed but all other options still apply

I have avoided using the built in disabled system as I could not get it functioning exactly like I wanted it to but there is a checkbox in about addons and the context menu entry. The latter being much quicker and less intrusive to access. Also no settings will be reset when toggling state this way as they are copied into temporary variables and stored until you re-enable the addon.

Some Screenshots

The panel disabled, the highlighting color is changed to red and all the panel elements are disabled, so no checkboxes or dropdowns can be activated while the state is disabled.
![ras1](https://cloud.githubusercontent.com/assets/2903711/11459162/0c5f9964-96c8-11e5-9590-31fe71541bff.png)

MouseMenu Entry showing the disable option. 
![ras2](https://cloud.githubusercontent.com/assets/2903711/11459161/0c5b3766-96c8-11e5-95ce-fd3f5d78a54b.png)

The icon beside the disable option will change reflect the current state ( disabled: red, enabled: blue (spoofing) or grey (real) )
![ras3](https://cloud.githubusercontent.com/assets/2903711/11459160/0c59e69a-96c8-11e5-8094-504afdddccd9.png)


The about addons ras page. Note the checkbox. The checkbox and mouse menu entry do the same thing. Using the  firefox "Disable addon" button will completly reset the addon . so be sure to use either the checkbox and or the mouse menu entry.  
![ras4](https://cloud.githubusercontent.com/assets/2903711/11459159/0c59ce1c-96c8-11e5-948a-e07c16d4cae8.png)

**Comment by RoxKilly** [comment]
@dillbyrne 
In `about:addons`, the checkbox in your last screenshot (Enable RAS) can only have 2 states: checked or unchecked.  How do you reconcile this with the tree states you explained? (disabled, spoofing, real)

**Comment by dillbyrne** [comment]
@RoxKilly  The addon state can be enabled or disabled.  If it is enabled you can choose to use your real profile or spoof a profile like you currently do, along with what ever options you select (now the options will work with the real profile too).

The checkbox and context menu will simply toggle the state from enabled to disabled and vice versa . The enabled state enables all your select options and your profile preference. While the addon is enabled you will either have a grey icon (real profile in use) or a blue icon (spoofed profile is in use) to indicate your profile preference. 


(Red) Disabled: Everything is disabled including UI and selected options are reverted to default state.
(Blue) Enabled: profile is spoofed and all other selected options still apply (or are reapplied if re enabled)
(Grey) Enabled: profile is not spoofed and all other selected options still apply (or are reapplied if re enabled)

Does that help to make it clearer ?

**Comment by RoxKilly** [comment]
It does thanks. When the addon is disabled from `about:addons`, the settings are lost right?  Like a "factory reset"?  On the other hand, if it's disabled from within the RAS UI, the settings are preserved in a temporary file that survives browser restart?

Looking forward to the update. Hope Mozilla doesn't take as long to sign it as it's taking to sign 0.9.5.3

**Comment by dillbyrne** [comment]
If the mouse menu or the checkbox in about addons is used then the preferences are preserved and re applied when you choose to reenable RAS.  If you choose the built in "Disable" button next to the "Remove" button like in the above screen shot, then the preferences will be reset like a factory reset.

The signing delay with 0.9.5.3 is partially due to the fact I was waiting on feedback about trying to get it back on to AMO . I asked the reviewer when submitting the last AMO version so I was waiting to hear back. I have since heard back and I have to contact them on IRC and see what I can do to get the full version back on AMO. The delay was also partially my fault as I have been quiet busy and not had a chance to get back to them. I plan to do that later today. 


 I have an issue open about signing so I will update that issue when I have some news.

**Comment by potholiday** [comment]
@dillbyrne Toggle system is Awesome!!! and sorry for the late reply. But where is the XPI files for Version 0.9.5.4 . no xpi files to download in  release page https://github.com/dillbyrne/random-agent-spoofer/releases

**Comment by dillbyrne** [comment]
@potholiday it will be on AMO if it passes review. Its the full version I have submitted so if it passes there will only be one version going forward, which will be signed and updated

**Comment by dillbyrne** [comment]
0.9.5.5 has passed full review and is available on AMO

**Comment by potholiday** [comment]
@dillbyrne Hey thanks for the update and i have updated my RAS to 0.9.5.5 from the AMO site. But it seems toggleing from panel is not working with my RAS. Did you implemented toggle in this update?

**Comment by dillbyrne** [comment]
@potholiday you can toggle using the mouse context menu entry or the check box option in about:config

**Comment by potholiday** [comment]
what about panel toggle system?(https://cloud.githubusercontent.com/assets/2903711/11459162/0c5f9964-96c8-11e5-9590-31fe71541bff.png). that is by clicking the icon of RAS in panel

**Comment by dillbyrne** [comment]
I have not clicked it in that picture I toggled using the mouse. I have the mouse over to show the icon tooltip. I can see how it appears misleading. I will be sure to update the documentation to illustrate what is happening more clearly.

RAS used to have a toggle system that used the panel icon when it still used the widget but after the switch to the action button addons could no longer listen for both mouse clicks. 

With the action button I am restricted to using the left click only and I have to use that to show the panel. This is why the mouse menu context menu is used instead.

**Comment by potholiday** [comment]
@dillbyrne Sorry for the misunderstanding but I thought we can toogle from icon menu. Any way thanks for the quick info :)

**Comment by dillbyrne** [comment]
@potholiday No problem. It was helpful because I know to make  the wording clearer when doing that part of  the manual.
