### ISSUE TITLE
RAS Popup Changed - Now Using Xfce OSD Instead

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#274]
Hi,

I'm using Slackware and with Firefox 38.0 ESR, I noticed RAS was using it's own style of a popup screen when starting Firefox for the first time, showing the profile it's using.

Slackware just did an update to the latest ESR 38.1.1, and I use xfce4-notifyd-config for my on screen displays, and now RAS is not showing it's own popup, now the xfce OSD is being shown when I start Firefox for the first time.

![ff](https://cloud.githubusercontent.com/assets/13072581/9183360/20ca5316-3f9e-11e5-8263-1ab148e93719.jpg)

**Comment by dillbyrne** [comment]
Hello @Geyup 

This is not a RAS issue it is mozilla issue. They made some changes to their library a while back which as far as I know wraps the native libraries. It happens on other desktop environments and other OS's too.

The changes they made to the notification code also caused notifications in RAS with images to sometimes not show, which is why I had to remove images as a work around until it is fixed. That particular issue happened in the firefox 36 cycle if I remember correctly.

**Comment by Geyup** [comment]
Hi,

I didn't say who's issue it was, I just said there's an issue... :)

Hopefully you can fix it, I must admit, I did like the look you had for the OSD. 

Keep up the great work!

**Comment by dillbyrne** [comment]
Thanks. I work with the notification library mozilla provides so they would have to make the changes you seek.

**Comment by Geyup** [comment]
Well, they are not really the changes I seek, it is afterall your program. So you'd be seeking this, if you wanted the default popup layout you originally created...
