### ISSUE TITLE
Add-on missing from menu toolbar in Ubuntu Firefox 40.0

### ISSUE THREAD

**Issue by timbowhite** [dillbyrne/random-agent-spoofer#277]
Hello.  Just upgraded to Firefox 40.0 on Ubuntu 14.04 x64, and the RAS add-on icon has disappeared from the menu toolbar.  It's also missing from the [+] Customize menu.  Other add-ons icons are still visible/accessible in the menu toolbar.

I double checked and RAS is still enabled in Tools > Add-ons > Extensions.

**Comment by dillbyrne** [comment]
Hello @timbowhite , I'm assuming you are using the AMO version, please state if this is not the case.

This is because mozilla have removed the widget module in the latest version of firefox. The current version of RAS (0.9.3.1.1-signed) on AMO uses the widget module but I have submitted an updated version which uses the new ActionButton module. It has been in the review queue since April 29th. I'm still waiting for it to be reviewed, so I can't do anything with the AMO version until I hear back from them.


If you don't want to wait on mozilla to review the new version, then you can use the current github version 0.9.5.3 , which is available at https://github.com/dillbyrne/random-agent-spoofer/releases

Note if you do decide to use the github version you must uninstall the AMO version first as they are not compatible do the vast changes between the two.

**Comment by timbowhite** [comment]
Thanks @dillbyrne!
For anyone else having the same problem and who doesn't want to wait for AMO version to be approved, do this:

1. Uninstall Random Agent Spoofer by going to Tools > Add-ons > Extensions, click "Remove" on the Random Agent Spoofer row.
2. Go to the lastest release of Random Agent Spoofer on github (currently Version 0.9.5.3 at https://github.com/dillbyrne/random-agent-spoofer/releases).
3. Scroll down to Downloads and click the "random-agent-spoofer.xpi" link, then click "Allow" when prompted.

**Comment by D1GITALelementz** [comment]
Cheers!

**Comment by DavidStaron** [comment]
@timbowhite

Thanks but that doesn't work for me, i get "Firefox has prevented this website from installing an unverified Addon".
Also, my user agent is now stuck on "Opera/9.64 (Macintosh; PPC Mac OS X; U; en) Presto/2.1.1" which breaks some websites :'(

**Comment by dillbyrne** [comment]
@DavidStaron Sorry about that I have had a version in the review queue since April 29th to prevent exactly this kind of thing from happening but it has been in the queue for three months now and I have no idea when it will be approved. 

The fault in this case is on mozilla, I have had the fix ready and uploaded well in advance of this and documented in the upload form that it was to address the deprecation of the widget module and add other updates. Again I apologize for any inconveniences caused.

**Comment by DavidStaron** [comment]
no problem, out of your control :)
