### ISSUE TITLE
Fake Signature of Browser

### ISSUE THREAD

**Issue by uuilid** [dillbyrne/random-agent-spoofer#279]
Is there a way to fake the signature of a browser. This option is not supported till now but it would be very useful. User Agent Spoof can be find out easily when the signature is not faked.

**Comment by RoxKilly** [comment]
What do you mean by signature? Would you show an example? How would I find my browser's signature?

**Comment by uuilid** [comment]
Every browser sends content and order of http-headers. The signature is the hash over browser headers. Your addon is great but it doesn't fake it. Therefore when you spoof the user agent there still remains the signature. Assumed you are using Firefox with your addon installed and your user agent is spoofed to chrome, the signature of Firefox would still betray that you are using Firefox. 

You can test your addon and read about the signature problem here: ip-check.info

**Comment by uuilid** [comment]
By the way, when you use Chrome with some proxies the above mentioned test site shows a different signature. Unfortunately, it doesn't work with Firefox even with your addon, Firefox's signature is always reveals. You should find a way to change also the signature to something random that no one can recognize it anymore.

**Comment by RoxKilly** [comment]
Thanks for the details.  It seems that this signature is based on the order of headers that your browser sends.  It would be nice if we could spoof the signature but I don't think Random Agent Spoofer can do anything about that. The website you referred to shows the following info when I hover over the signature:
> "Unfortunately current web browsers do not allow to change the order of the headers sent by them"
So the bad news is that this signature can be used to find out which browser I am using and to find out that I am trying to hide my identity by spoofing my User Agent string.

The good news is that simply knowing that my real browser is Firefox is not enough to track me; this signature cannot be used to track me because it's a generic signature. Several computers in my home with different IPs, user-agents, browser plugins etc... have the same generic Firefox signature.  This means that a tracker cannot use the signature by itself to recognize me specifically.  Even the Firefox browser on my smartphone has the same signature, so I'm not worried about it.

**Comment by dillbyrne** [comment]
I am aware of this and I have tried to change this before by manually sending some headers in different orders but it made no effect on the signature.    

Please search for existing issues before opening new ones. See #79

**Comment by ALIBERNANKE** [comment]
one question if i want to use a complete browser profile (think screan depth.size. to http header) but i want that profile to be changed in every x amount of time what addon do You recommend ?
