### ISSUE TITLE
Question: HTTP session, Signature, Spoof Accept?

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#290]
Hi dillbyrne,

Is there anything that can be done in RAS to protect the ```HTTP Session``` & ```Signature```?

If I check under ```Headers``` the 3 ```Spoof Accept``` options, when I use Jondonym IP check they all come back as a medium level. If I uncheck all of them, Jondonym rates them all green good. Hmm I know Jondonym has their own agenda I'm sure, but for the most part it has seemed reliable with information...

http://ip-check.info/?lang=en

My understand using the Spoof Accept makes your browser fingerprint standout more?

thanks

**Comment by RoxKilly** [comment]
Jondonym recommends settings that are very common, so that you will be difficult to distinguish.  For this "crowd protection" to work though, your User Agent string should also be common and should match your Headers.  If you use a fake user-agent provided by RAS but real headers because you unchecked `Spoof Accept`, your browser will **really** stand out; you might for instance have the UA of a Safari browser, but the other Headers of a Firefox on Windows browser. `Spoof Accept` allows the [spoofed] headers to match your [spoofed] User-Agent, thus making your fake profile look more authentic.

Jondonym and RAS try to achieve privacy by using different paradigms.  Whereas Jondonym tries to hide in the crowd by using a single very common browser signature, RAS tries to make itself difficult to track by regularly changing the signature.  In practice, this means that although your current Spoofed User-Agent & Header settings might stand out more than Jondonym's, with RAS your settings will change often, making you really difficult to track.

**Comment by Geyup** [comment]
Ok thanks

**Comment by dillbyrne** [comment]
RAS headers match the currently spoofed profile so you will  have chrome headers with the and the chrome user agent and google inc as the vendor when you select a chrome profile for example. 

Jondonym recommends their browser or the tor browser and makes their comparisons to them. Both of those browsers are based on FF so that is why it shows green for those headers . 

If you intend to use RAS it is strongly recommended to keep the accept headers checked or you will definitely stand out more due to profile inconsistencies.

See https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json and it will become clearer.

**Comment by Geyup** [comment]
thanks
