### ISSUE TITLE
whitelist option to only spoof javascript/header options

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [dillbyrne/random-agent-spoofer#292]
this might sound weird, but i think it might be useful if there was a whitelist option which would disable the use of the profile(useragent etc).

to make it clearer, an example is facebook.com where i want to continue randomly spoofing everything, but if i could give the site my real screen size, the website might function better. however if i whitelist facebook.com for 'screen' option, it will also have to use the static whitelist profile for useragent etc. 

i cant  think of a good name, but lets say 'noprofile' for now. something like:
{"url": "facebook.com","options": ["noprofile","screen"]},
that way for facebook.com, the only thing not being spoofed would be 'screen'. it would continue randomizing the profile as usual.

this is probably confusing and complicated tho so maybe nobody else would be interested in this becoming a feature

**Comment by B00ze64** [comment]
Well Well, I was going to suggest essentially the same thing. I am about to install the "GitHub" version because I need to whitelist some sites that break with spoofed ETags and *for some unfathomable reason, the normal AMO version doesn't support Whitelisting*. I do NOT use "Agent" spoofing at all with RAS, I use "Real Profile" all the time, and I want my Whitelist to ALSO use this. I do NOT want to manually edit the Whitelist profile each time I upgrade Firefox to bring the Agent string up to date. There should be a checkbox to enable to disable the "Whitelist Profile" ... please please please pretty please :-).

**Comment by dillbyrne** [comment]
This is done now and will be available in the next release.

Now when the real profile is selected you can still use the script injection and whitelist options.

The injection script will not inject the whitelist profile while the default profile is in use for all other profiles it will inject the whitelist profile if there is a rule for that particular url.

So no changes are needed to the current whitelist format the addon will know when to apply the whitelist profile and when not to.
