### ISSUE TITLE
Icon Missing

### ISSUE THREAD

**Issue by albe52** [dillbyrne/random-agent-spoofer#294]
Using Win7-64b recent upgrade of FF to 40.03 resulted in missing RAS icon.  i have read some of the other posts regarding this issue.  I removed RAS and reinstalled but to no avail.  Any fix yet?   Thank you.  It's a great add-on.

**Comment by albe52** [comment]
FYI  I just tried installing RAS on a different user account on this box that FF is installed for.  No RAS icon for 40.03

**Comment by jason-collier** [comment]
I'm having the exact same issue: Win7, 64 bit, Firefox 40.0.3 and no icon. I uninstalled and reinstalled but still no icon.

**Comment by jason-collier** [comment]
Also having the issue on Windows 8.1, 64 bit, running Firefox 40.0.3.

**Comment by TehEnforce** [comment]
FF 40.0.3 Mac here aswell. No icon ://

**Comment by ka223** [comment]
Icon is available with Version 0.9.5.3, Firefox 40.0.3 and 64Bit Lubuntu.
https://github.com/dillbyrne/random-agent-spoofer/releases

**Comment by dillbyrne** [comment]
Hi all sorry for the delay in my response.

The one on AMO (0.9.3.1.1-signed) is using the old widget API which has been deprecated. I have a version on AMO to fix this since April 29th and it has been in the review queue since . If you are using the AMO version and don't want to wait until they decide to review it you can install the github version at https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.3

**Comment by albe52** [comment]
AMO?

**Comment by dillbyrne** [comment]
@albe52 AMO == https://addons.mozilla.org
