### ISSUE TITLE
Screen Resolution and JavaScript version via browserleaks.com

### ISSUE THREAD

**Issue by PuntoBanco** [dillbyrne/random-agent-spoofer#295]
Hi,
i check like running RAS via http://www.browserleaks.com/javascript
I see incorrect version of javascript (Version 1.5 for all browsers)
and real (don't spoof) screen size (ScreenResolution) of working area (in window and iframe.contentWindow mode) 

possibly fix it?

Alexander

**Comment by sharan01** [comment]
i think script injection option must be checked for screen resoultion spoofing to work

**Comment by dillbyrne** [comment]
@PuntoBanco The script injection code so far does not account for all cases just the most straight forward javascript attempts to get the screen dimensions, it still needs more work 

On browserleaks.com, it says it uses `screen.width + screen.height + screen.colorDepth + screen.pixelDepth` in the resolution field but we take care of all them already so it is using other values to determine the working area.

I can block the `iframe.contentwindow` with

`content += 'Object.defineProperty(HTMLIFrameElement.prototype, "contentWindow", {value: undefined});';`

in the injection script for example but that will break that functionality completely. Ideally we would return a modified 'windowProxy' object with our spoofed values.  I have not found any documentation on that object however.

I don't touch the javascript version. If you go to that site with no addons it will still say 1.5  I suspect they just forgot to update the check since they wrote that code

**Comment by PatSpiegel** [comment]
sandbox + "content-document-global-created"

**Comment by dillbyrne** [comment]
This is fixed with the new frame script injection code. Thanks for the bug report
