### ISSUE TITLE
Compatibility with the Pushbullet plugin (Firefox)

### ISSUE THREAD

**Issue by dugite-code** [dillbyrne/random-agent-spoofer#296]
I have been attempting to get random-agent-spoofer to allow the pushbullet plugin to login but have been unsuccessful.

If I set RAS to Real Profile Pushbullet won't log in. However if I do so before closing Firefox Pushbullet will work, and continue working even if RAS is then activated, on next start.

I have attempted to whitelist (using `"options":["authorization", "referer", "xff", "via", "ifnonematch", "windowName", "canvas", "screen", "date" ]`) the following domains:

```
pushbullet.com
websocket.pushbullet.com
zebra.pushbullet.com
static.pushbullet.com
api.pushbullet.com
accounts.google.com
```

I also whitelisted `resource://jid1-bycqofyfmbmd9a-at-jetpack/pushbullet/data/panel.html` to see if that helped but no luck.

Obviously I did fully disable RAS to make sure it was the actual cause of the issue.

Edit:RAS v0.9.5.3

**Comment by dillbyrne** [comment]
What happens when you try it with the script injection option disabled ?

or all headers options unchecked except the three accept headers  ?

or uncheck  the standard options  to see ifany of those are causing the issue. 

I have found the following to cause the some issues on sites.

Disable local dom storage
Disable memory cache
Disable disk cache
Disable network cache
