### ISSUE TITLE
In the new version of Random spofer* . This no have the option of hide the messages of change of agent

### ISSUE THREAD

**Issue by merlinnusr** [dillbyrne/random-agent-spoofer#300]
Pls. Admin add this

**Comment by merlinnusr** [comment]
Yes , my english is a full shit

**Comment by Orkel** [comment]
Yeah seriously wtf the add-on updated by itself while I was away and is now spamming messages since I have the per request option activated, how come you guys could forget the option to hide messages, it's a good add-on overall but this is a very bad move.

And while we're at it why the browser pool has the exclude buttons instead of include ? I would like the spoofer to choose in a pool of recent PC browsers since some websites can disable some content when your browser is too old. But to achieve that i would have to exclude all the browsers i want not of instead of including the few ones i want.

**Comment by Orkel** [comment]
Nevermind you can disable notifications by going to tool > addons > disable notifications

We still need include based browser pool tho.

**Comment by wmax641** [comment]
The option to disable notifications has changed location;

Go to: about:addons
Find RAS and click "Preferences"
And somewhere at the bottom of the huge wall of text will be a tick box [Show Notifications]

v0.9.53

**Comment by dillbyrne** [comment]
@wmax641 Thanks

@merlinnusr see above post and attached screenshot 

![s](https://cloud.githubusercontent.com/assets/2903711/10871221/d606923c-80d8-11e5-8593-90c655ab726b.png)
