### ISSUE TITLE
Use everything without changing the User agent

### ISSUE THREAD

**Issue by Garve** [dillbyrne/random-agent-spoofer#301]
Hi!

Changing the user agent sometimes breaks sites, but I can't use all the other functions without also changing the user agent. Does it have to go together, or is there a way to keep my normal user agent and still benefit from  stuff like window.name and screen resolution spoofing?

Thank you!

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think this is kinda related to my issue #292 . it would be nice if there were more customizable per-site options instead of the current whitelist feature. 

@Garve a workaround for ur case is to use https://addons.mozilla.org/en-us/firefox/addon/uacontrol/ and https://addons.mozilla.org/en-us/firefox/addon/user-agent-js-fixer/
set the default action on uacontrol to 'Normal' (this will let RAS do its useragent spoofing on all sites)
then add a uacontrol rule for ur broken site and give it the real string of ur browser (or a generic one which works). then in this case, RAS will work as normal but uacontrol will override with its useragent for that website. (dont select 'normal' in this case, with RAS enabled, normal means RAS. type in the actual useragent you need)

**Comment by OdinGitDat** [comment]
I came here to submit an issue about none of the header and script injection working. I disabled the ua spoofing because I know that it does not increase my privacy, fingerprinting is about blending in, using multiple 'fingerprints' doesnt really blend you in (there isnt even an option for a custom ua string). Anyway I digress, I didnt notice that none of the other features work without it. Why does it work like that? I just want to use the script injection features!

**Comment by RoxKilly** [comment]
> I disabled the ua spoofing because I know that it does not increase my privacy, fingerprinting is about blending in, using multiple 'fingerprints' doesnt really blend you in -@OdinGitDat
I disagree partially. A well-implemented multiple-fingerprint system can be effective. The purpose of fingerprinting is tracking: to recognize the target the next time you see it, because a good fingerprint doesn't change. If I have a different fingerprint each time a tracker sees me, and it has no way to link one fingerprint to the next, it will think the fingerprints belong to different targets and will be unable to track me over time.
I do agree that changing the UA by itself is not very good defense because there are many other methods to establish persistent tracking, but all fingerprint-based tracking rely on the fingerprint being (1) consistent over time, (2) unique or at least rare.

**Comment by B00ze64** [comment]
@OdinGitDat : I agree with you, randomly changing the UserAgent is mostly useless - Changing it just once is also mostly useless, safety in numbers and all that; it's best to leave it alone. I also use RAS for the other options it has, especially ETag spoofing. Are you SURE that the injection options (e.g. ScreenSize etc) do not work when not using the random agent (i.e. Real Profile)? Because all the "Standard Options" do work...

**Comment by B00ze64** [comment]
Just so it's clear to the author that not everyone uses RAS the same way, I also use RAS **only** for miscellaneous options is has (ETag spoofing, etc) and **not at all** for Agent spoofing. In my humble opinion Agent String spoofing (for the purpose of privacy) is useless, it's best to leave it alone (safety in numbers and all that). It also lets sites code for a specific browser, which I am sure some sites still do...

@OdinGitDat : Head over to bug #272 and have a look at proposed change which will just about break the addOn for me; provide feedback please.

Thank you.
Best Regards,

**Comment by OdinGitDat** [comment]
ATM, the only options that still work when I have the 'real profile' enabled are the standard options. My solution for now is to just select any user agent that RAS provides and then with uMatrix override that ua-string with the real one of my browser. It's a bit higgley piggley, but it works for me.

**Comment by B00ze64** [comment]
I had a look at uMatrix but it's a bit much for me; noScript is sufficient. I tried it with UserAgentSwitcher tho, and it works so long as I change the userAgent with UAS **after** changing it inside RAS (but I might have to do this every time FF starts). Also, this breaks my ACCEPT languages (I live in Canada, I like that to be set to both EN and FR). RAS really needs to allow changing other options, whitelisting, etc, ALSO on the "Real Profile" and unfortunately, this is not where the author is going :-(

**Comment by dillbyrne** [comment]
@B00ze64 RAS as of 0.9.5.4 will have support for multiple Accept language headers see https://github.com/dillbyrne/random-agent-spoofer/wiki/Headers-Tab-Usage If you submit Canadian headers for fresh installs of the available browsers  you can find I'll add them.

The profiles used RAS are not simply user agent strings, there are many attributes that are also present in the real browsers so comparing a RAS profile terms of fingerprinting prevention efficacy to simply spoofing a user agent string is a not really a fair comparison.

The reason some sections are tied to profile spoofing is that they make use of profile data. The script injection currently injects vendor info obtained from the profile. The screen size (if the Profile option is selected) and color and pixel depths are obtained from the current profile so they all match up . The accept headers are also defined by the current profile as you will stand out if they do not match the rest of the profile. 

> Just so it's clear to the author that not everyone uses RAS the same way
I'm well aware of this. I make no claim that RAS is even close to finished, many of the features are still first iterations. I can only work on it in my spare time which is not very much these days but slow progress is better than no progress.

As for the request at hand  It should be possible but the accept headers will still be tied to the selected profile.

**Comment by B00ze64** [comment]
Good day @dillbyrne 

> The profiles used RAS are not simply user agent strings, there are many attributes
> that are also present in the real browsers so comparing a RAS profile terms of 
> fingerprinting prevention efficacy to simply spoofing a user agent string is a not 
> really a fair comparison.

Agreed, but we can see which values each profile can have in the WhiteList profile (platform, accept, vendor, etc) and I prefer most of these to be the real values. For instance, I prefer a website to offer me the x64 version of a binary because it sniffed OS/CPU from my browser; we are enough people with all these values the same that I'm fine with sending my real values to websites. I think eTag spoofing is more important than all the values in the profile.

> The reason some sections are tied to profile spoofing is that they make use of profile data.

Nothing prevents RAS using the real values tho; just think of it as a profile...

> The script injection currently injects vendor info obtained from the profile. The screen size
> (if the Profile option is selected) and color and pixel depths are obtained from the current 
> profile so they all match up . The accept headers are also defined by the current profile 
> as you will stand out if they do not match the rest of the profile. 

For screen size and depth, you have an option so we can override it (pretty cool). I understand now how more how RAS works, but I still think we could have all these non-standard options work just fine with the real profile.

> I'm well aware of this. I make no claim that RAS is even close to finished, many of the features
> are still first iterations. I can only work on it in my spare time which is not very much these days
> but slow progress is better than no progress.

Oh, I'm not complaining, it's just that your addOn is the **only** addOn I know of that can spoof eTags (for now) and it also has many other cool options, it's a shame we cannot use them unless we pick a specific browser to emulate. Just fill-up a profile structure with all the real info from the browser, just like a pre-defined profile, then the rest of the code doesn't have to change, it still pulls all the info off of a "profile" but this profile is the same as the real thing. Hmm, this makes me think you could add a "Custom" profile, similar to the Whitelist profile, and have a checkbox next to each value to use browser default or not - this way we could build our own profile, and if we wanted, put a checkmark next to ALL the values and it would be the same as using the real profile.

Anyway, I do appreciate your efforts, thanks!

**Comment by dillbyrne** [comment]
This is done now and will be available in the next release.
Now when the real profile is selected you can still use the script injection and whitelist options.

The injection script will not inject the whitelist profile while the default profile is in use for all other profiles it will inject the whitelist profile if there is a rule for that particular url.
