### ISSUE TITLE
Switching from Github version back to AMO version of the add-on

### ISSUE THREAD

**Issue by fflintstone** [dillbyrne/random-agent-spoofer#314]
I made the mistake of installing the Github version of the add-on, but would now like to return to using the AMO version (so I can have the version that's "verified for use in Firefox"). I've tried uninstalling the add-on, restarting Firefox, then installing the AMO version, but then I find that a lot of features, such as the whitelist, are disabled and unusable. Is there a way to go back?

When I first went from the AMO to the Github version, I hadn't seen the instruction to uninstall first, so I didn't do that part at that time - could that be part of the problem?

I like this add-on a lot, and want to keep using it, but since Mozilla will soon stop us from using unverified add-ons, I think it would be beneficial to switch back, so any advise would be appreciated.

**Comment by dillbyrne** [comment]
Hello @fflintstone  

The whitelist and script injection are intentionally disabled in the AMO version due to feedback from AMO reviewers about certain aspects of the script injection code such as screen size spoofing etc.

I am hoping to get the full version back on to AMO. I need to talk with some AMO folks and see what can be done . 

The AMO and github versions are not  interchangeable as I stated in the instructions because they are different stages in development, with the AMO version behind the github version.

Apart from starting a new browser profile https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles, you can try uninstalling your current version and manually resetting any prefs that don't change back.  

you can find a list of the preferences used in the AMO version at
https://github.com/dillbyrne/random-agent-spoofer/blob/AMO-limited/lib/PrefServ.js

 and the prefs for the github version at
https://github.com/dillbyrne/random-agent-spoofer/blob/master/lib/PrefServ.js 

Once they have all been reset then a fresh install of what ever version you want will should work.  if all else fails a fresh profile will work as stated above

**Comment by fflintstone** [comment]
Thanks for the feedback.  Since I appreciate the whitelist feature so much and would lose it by switching back to the AMO version, I guess I'll stick with the unapproved version until Firefox forces the issue.  At that time, I'll try your suggestion for resetting.  I've been doing some reading on the internet, and (if I'm correct about what you're saying) I understand how to run the javascript listed above.

Speaking of the whitelist feature, I have the following entries, but it seems to ignore the one for "mozilla.org" (and maybe some of the others).  Am I doing something wrong?:
[{"url":"cwtv.com"},{"url":"fidelity.com"},{"url":"mozilla.org"},{"url":"netflix.com"},{"url":"play.google.com"},{"url":"s.ytimg.com","options":["canvas"]},{"url":"yahoo.com"},{"url":"youtube.com","options":["canvas"]}]

**Comment by dillbyrne** [comment]
The full version is now on AMO so I'm closing this now
