### ISSUE TITLE
Checkbox to disable notification when profile changes

### ISSUE THREAD

**Issue by essembeh** [dillbyrne/random-agent-spoofer#327]
It would be nice to be able to enable/disable these notifications.

Use case, if I want a new random profile every request, I get flooded by notification (sound + popup).
Maybe it is already possible to disable (or a workaround) them but I couldn't figure out how.

Thanks

**Comment by dillbyrne** [comment]
Hi @essembeh  see https://github.com/dillbyrne/random-agent-spoofer/issues/300

**Comment by essembeh** [comment]
Ok, thanks for the workaround, I didn't find #300 before opening this one.

I say workaround because the procedure to enable/disable notifications is quite tricky (> 3 clicks).
Maybe you could reopen the ticket to implement the option directly in the menu?

By the way, thank you for the answer and for this useful addon ;)

**Comment by dillbyrne** [comment]
I moved the option there because it is not something that users generally change frequently, they either want them enabled or they don't. Also you can still mouse over the addon icon in the toolbar to find out what the current profile is if you have them disabled so the notifications for the most part inform you a change has taken place.

As for the sound , that is due to your platfrom and how it handles notifications ( libnotify (linux) / growl (osx) / whatever windows uses). 

Thanks, I'm glad you like it

**Comment by Exagram** [comment]
@dillbyrne As a user, I expect configurations to be found in visible places, like the Options panel. The about:addons page is an obscure place, so I'd label it as opaque. As a developer I found the "Show Notifications?" option by visiting Github/issues. A regular user won't know of Github/issues and would assume such functionality is missing. This is not the best user experience. If it is true that the user doesn't frequently change the option, it doesn't follow that we should hide it in such an obscure place. So let us place the "Show Notifications?" into the Options panel. Thoughts?
