### ISSUE TITLE
Firefox 43 deactivate random agent spoofer

### ISSUE THREAD

**Issue by bubbelbe** [dillbyrne/random-agent-spoofer#332]
There is no signature for random-agent-spoofer, from now only addons with signature works on firefox.
What will that mean for the future?
Greetings

**Comment by dillbyrne** [comment]
I'm literally uploading a new full version to AMO right now.

**Comment by anoadragon453** [comment]
From [Mozilla Wiki](https://wiki.mozilla.org/Addons/Extension_Signing):

The Developer Edition and Nightly versions of Firefox will have a setting to disable signature enforcement. There will also be special unbranded versions of Release and Beta that will have this setting, so that add-on developers can work on their add-ons without having to sign every build. To disable signature checks, you will need to set the `xpinstall.signatures.required` preference to "false".
* type `about:config` into the URL bar in Firefox
* in the Search box type `xpinstall.signatures.required`
* double-click the preference, or right-click and selected "Toggle", to set it to false.

**Comment by potholiday** [comment]
Even I have faced the same problem with my firefox 43 version. thanks to @anoadragon453 suggestion I disabled signature feature and now its working. @dillbyrne what will happen after 44 version. I really like RAS in github it has more features :(

**Comment by eNTi** [comment]
i hope there will be a user whitelist for certain plugin signatures...

**Comment by dillbyrne** [comment]
@potholiday it is the full version that is in the review queue on AMO. So if that passes review you can upgrade to the full version which will be signed and hosted on AMO.

@eNTi 0.9.5.4 is the full version so if it passes review it will allow you to do everything the current github version can do along with all the new stuff in 0.9.5.4

**Comment by Wannabe-Programmer** [comment]
@dillbyrne I noticed you haven't released version 0.9.5.4 on Github... I'm guessing that's because you don't want users to disable the signatures - {xpinstall.signatures.required:**false**}

**Comment by RoxKilly** [comment]
@Wannabe-Programmer, see the last few posts from #228 where dillbyrne explains his decision.

**Comment by dillbyrne** [comment]
The xpi will be on AMO if they sign it. I want to have a single version going forward as maintaining two versions is a pain and since they will have to be signed anyway it makes sense to use AMO. Hopefully it will pass the review this time due the changes in the script injection code

**Comment by mva1985** [comment]
I love this extension

thanks @anoadragon453  for the explanation on how to turn off signatures

**Comment by dillbyrne** [comment]
0.9.5.5 has been approved and is now signed by AMO. :tada:
