### ISSUE TITLE
Whitelist to disable RAS entirely for given domain

### ISSUE THREAD

**Issue by danielcra** [dillbyrne/random-agent-spoofer#353]
Hi there,

Would it be possible to change the whitelist feature such that it disables RAS entirely for a given domain? With 0.9.5.5, when I add to the whitelist box: [{"url":"domain.org"}], then features from "Options->Standard options" are still active for "domain.org". 

Effective tracking protection breaks many sites and to unbreak them,there needs to be an easy way to disable tracking protection entirely, not just send the real UA. I know I can (again) disable RAS using the context menu. But for many sites, when I log in with RAS active and then run into a problem and disable RAS, the site forces me to log in again. That's a bit inconvenient.

Thanks

**Comment by dillbyrne** [comment]
This is not possible as the standard options are global browser preferences and affect all sites, the only reason the script injection and headers can be handled on a site by site basis is due to the fact we can access the headers before they are sent and dynamically modify the injection script based on the user's settings.
