### ISSUE TITLE
Whitelist doesn't work for me

### ISSUE THREAD

**Issue by Drugoy** [dillbyrne/random-agent-spoofer#357]
I use default whitelist which consists of 3 items ``[{"url":"addons.mozilla.org"},{"url":"play.google.com"},{"url":"youtube.com"}]``, and since one of which is ``{"url":"addons.mozilla.org"}`` I expect RAS to not spoof UA for addons.mozilla.org.
I've disabled all other addons, restarted firefox, visited the given site.
Result: UA is spoofed, the site tells me to get Firefox if I want to install add-ons.
I tried restarting the browser and visiting addons.mozilla.org a few more times - the result is the same.
If I select in RAS to not spoof the UA - the site works fine, I can easily install add-ons.

So the problem probably has something to do with prefs.js, since I couldn't reproduce it on a clean profile
What prefs.js setting might affect the problem?

W7SP1x64, Fx 43.0.4 x64, RAS 0.9.5.5

**Comment by malimM** [comment]
I ahve the exact problem, whitelisting isn't working on Developer Edition 47.0a2

**Comment by fflintstone** [comment]
I noticed the same problem that whitelisting stopped working in FF 44.0.  I also agree that it's really a problem when visiting addons.mozilla.org, so as a result, I have spoofing turned off most of the time now.  I hope this gets fixed sometime soon.

**Comment by Drugoy** [comment]
I feel like this add-on has now become an abandonware.
I hope I'm wrong and I hope that the developer will make the new version not only without this bug, but also fully compatible with the new Firefox platform (e10s, Add-on SDK, WebExtensions).

**Comment by dillbyrne** [comment]
This is due to #365 which relies on script injection . 

@Drugoy Firstly the addon has always been built using the addon sdk. 

Secondly it was mozilla's changes that broke it and as usual I had checked the developer advisories before that version shipped and there was no mention of changes to components that RAS uses. So I didn't notice until very close to the release.   

Thirdly  I have been working to fix it  as soon as I discovered but as the problem was due to changes made by mozilla and the nature of the problem itself it was difficult to find the source before even beginning on a solution.

I have spent a great deal of time trying many different scenarios trying to find the source of it so if you are not seeing updates it is not because I am not working on it. If you had been following the issue above you would see I posted an update about a proposed fix but it means removing most if not all of the existing script injection and whitelist related code and writing new code that make use of frame scripts.

I only have limited time too and as this is the most pressing issue it has my priority. I have not abandoned it. You will see updates when I have a working solution. 

Also consider the fact I have mentioned this on the AMO page and there is an issue already open for it.

https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

**Comment by Drugoy** [comment]
@dillbyrne I'm glad I was wrong about this add-on being abandoned and it was nice to finally hear from you. I'm a plain user, not a developer, I don't know much about things happening under the hood, I know that Mozilla recently pushed (and will continue to do so) lots of changes that break a lot of stuff.
> If you had been following the issue above

No, I was no following it since it was filed later than this one and I followed your bug reporting guide prior to filing this issue (I searched for the possible dupes among other opened issues and provided the tech info you asked, it's just I omitted the part that says that the issue reproduced on a clean profile too, since otherwise I probably wouldn't even report this issue).

It's good to know you finally found the reason of this bug happening.
