### ISSUE TITLE
User agents Update

### ISSUE THREAD

**Issue by kamiluss** [dillbyrne/random-agent-spoofer#390]
Hello

how can I update the user agents list in my Random Agent Spoofer installed in Firefox. Today I use plugin version 0.9.5.5.

I see that in Code download file called useragents.json is more browsers agents than in my install plugin.

Can you help me about that?

Thank you.

**Comment by dillbyrne** [comment]
No one has the updated versions yet. I have to fix the script injection bug and I'll release a new version as soon as I do with updated version.

**Comment by kamiluss** [comment]
Ok thx for answer :)

**Comment by RoxKilly** [comment]
@dillbyrne  I'm sure you've thought about this: why did you design the addon so that the profiles available can only be updated when the addon itself gets updated?  Why not a model whereby the profiles get updated more dynamically the way uBlock Origin and Adblock Plus update their block lists?

**Comment by dillbyrne** [comment]
@RoxKilly It was done like this as the profiles are more than a simple user agent string. Most users would not update them correctly. If users are not bothered to submit a profile then they can hardly be expected to maintain a list. 

Also what constitutes a profile has changed as RAS has evolved so each time this required changes to the profile structure and would have caused many issues for people  not using the new structure and code would have had to be written each time to update users profile lists to the correct format.  Basically it would have been a mess.

Keeping the profiles tied to RAS means I can ensure it all matches and get on with developing and fixing bugs. The release cycle is normally not too long. This time being the exception since the ff45 update broke all script injection and a new method has to be implemented.

Users can still update the user agents via a pull request.

**Comment by dillbyrne** [comment]
Has anyone got windows 10 and or a newer android phone with chrome installed ?

**Comment by RoxKilly** [comment]
Sorry @dillbyrne , Still on Win 7 here.

**Comment by franco640** [comment]
Hi @dillbyrne I have windows 10 if you want me to test

**Comment by dillbyrne** [comment]
@franco640 I got the information I needed for win 10 from a friend. Thanks anyway 

If anyone has the latest Iphone I need the following outputs 

http://browserspy.dk/browser.php to get the general profile

http://browserspy.dk/accept.php to get the headers

http://browserspy.dk/screen.php to get the screen information

**Comment by hdatma** [comment]
http://browscap.org/
