### ISSUE TITLE
Spoof Accept-Language : Other languages ?

### ISSUE THREAD

**Issue by publicstorage689** [dillbyrne/random-agent-spoofer#405]
Hello,
I just installed the extension, but i'm getting only few languages,
or theses linked to firefox languages packs installed on the machine ?
How to manager other languages ? (for now on the firefox languages pages only fews are available for firefox 43.0, and i installed some but nothing appear in the Spoof Accept-Language list).

Thanks

**Comment by dillbyrne** [comment]
The language packs have nothing to do with it see https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json

and https://github.com/dillbyrne/random-agent-spoofer/wiki/How-To-contribute#improving-support-for-more-than-one-accept-header-language

Each profile has to be tailored so the headers match the rest of the profile so I have added support for some language headers when I have the correct data for that language header and if the the profile changes after a period of time and the new profile does not suppoft the previous language header then the fallback language header is the default "en us" version for that profile.

Firefox provides all versions of the browsers with different language headers where as chrome only gives you a single download and it defaults to your region. With chrome I only have access to the header for my region. I need users to submit their region specific chrome headers in order to add them to RAS.
