### ISSUE TITLE
[Suggestion] Changing profile  on every page or every domain

### ISSUE THREAD

**Issue by Kraxys** [dillbyrne/random-agent-spoofer#412]
Hi,

Currently, there are several ways to change periodically profile: each time the browser start, on a regular time basis or on every random instant. But changing profile on a regular or randomly time basis sometimes appears to disruptive: on some sites, when the profile change while I'm logged in, the site sees something weird and asks me to log again (with the new profile), etc every time the profile changes, making mandatory for my to select the option "change periodically: no", which is not sufficiently disruptive for me.

So, why not add an option such that "change profile on every page" (or better on every domain)?

**Comment by dillbyrne** [comment]
Hi @Kraxys . 

This has been requested before and I have already tried a similar approach in the past. The problem is that a large portion of the profile related attributes are global settings in firefox so changing them affects every site. Also many sites include third party requests that can cause a race condition when using multiple tabs. Then there was also issue when mobile and non mobile profiles were used together. 

Some of it could be done with script injection but then you still have headers to contend with. The current whitelist is done in such a way and handles headers but only for the whitelisted domain.  All requests to non whitelisted sites (eg jquery) would be using the currently spoofed profile and not the whitelisted profile.

If you want to try it feel free to fork it but I will not be implementing it due to the reasons outlined above.
