### ISSUE TITLE
Privacy-detrimental defaults reset when add-on is disabled

### ISSUE THREAD

**Issue by noname-123** [dillbyrne/random-agent-spoofer#423]
When the add-on is disabled and re-enabled in the add-on page, Firefox's settings on various privacy-affecting things have been set to default, even though they were altered before the add-on was installed. Settings such as the safe browsing, malware check, WebRTC, etc. Even Do Not Track is disabled (!)

This happens the instant the add-on is DISabled. I read some other issue that this happens also when it is uninstalled.

This feels wrong in an add-on that is intended for boosting privacy. I hope it will be fixed soon.

**Comment by fspoettel** [comment]
I can confirm this behavior. The code in question is [RaS.js#402](https://github.com/dillbyrne/random-agent-spoofer/blob/master/lib/Ras.js#L402). There should at least be a warning about the behavior somewhere in the docs as it can conflict with user expectations. (I checked and did not immediately find one)

**Comment by dillbyrne** [comment]
I have a built in option for toggling it on or off. It is currently broken in the current release due to mozilla removing a pref but I have added a [fix](https://github.com/dillbyrne/random-agent-spoofer/commit/49c2f310f1cf9c8c496c12785f8c0a56fba43bac) that will prevent that in the future and it will be available in the next release.

https://github.com/dillbyrne/random-agent-spoofer/wiki/Frequently-Asked-Questions
https://github.com/dillbyrne/random-agent-spoofer/wiki/Context-Menu-Usage

**Comment by noname-123** [comment]
I'm new to GitHub, so I'm not sure this will work since it says "closed", but I'll try:

I don't see how setting stuff to default is "reverting changes". For me, that was _making_ changes, as I myself had previously changed the settings, and what RAS did was to change that to something I hadn't set.

If it isn't possible to save the settings in a file (locally of course, so that it doesn't pose a privacy risk), and revert to that except items that has been changed manually later, can't there at least be a question dialog like "Do you want to keep the current settings or revert to Firefox default settings?"

What it does now seems clunky, treacherous against the user, and unsafe.
