### ISSUE TITLE
Settings revert.

### ISSUE THREAD

**Issue by forkoz** [dillbyrne/random-agent-spoofer#428]
I turned off random spoofing and picked a profile to use. RAS icon is red and my settings for headers and options keep reverting to defaults when I restart the browser.

I'm still on firefox 44.0.2, maybe some of this is resolved in recent commits but I'd have to download all the toolchain and compile it. Wish you had auto-build/nightlies.

**Comment by bonbonboi** [comment]
Hi forkoz, Would you provide us more info about your system, OS? RAS Version? 
Meanwhile check out if you really enabled RAS, take a look here:
[http://oi68.tinypic.com/20aaueu.jpg](url)

**Comment by forkoz** [comment]
Latest RAS version available as binary... 9.5.5 I checked your pic and set that check box. The enable/disable is broken anyways on FF 44+

This is really bad; I have options and a profile selected but RAS is off unless I go into obscure menu #3?

**Comment by bonbonboi** [comment]
RAS is not broken totally, yes some features but not all, I'm on FF 47.0.1 and RAS is working very well, I suggest you to create a new FF profile, install RAS and see the result, sometimes could your current FF profile is broken or/and has some add-ons conflicts. If that didn't help, then there is something wrong with FF itself. If you are on Windows, you need to double check that your system is virus/spyware/adware free, since Windows catch a lot of those kinds of stuff, some of them inject their code/add-ons even with a clean FF profile.

**Comment by dillbyrne** [comment]
@forkoz I have fixed this issue that you reported already #373 It will be in the next release.

A mozilla update broke RAS's built in toggle system. It has since been fixed and will be available in the next release.
