### ISSUE TITLE
Whitelist to disable all RAS functionality for a site

### ISSUE THREAD

**Issue by danielcra** [dillbyrne/random-agent-spoofer#442]
Hi,

Could whitelist be enhanced so that it disables all RAS functionality for a site, not just the user agent and some selected other features?

Essentially adding a whitelist entry like 
{"url":"test.com"} or
{"url":"test.com","options":["*"]}
should disable all RAS functionality.

The effect should be the same as RMB->Disable RAS, which is what I have to do a lot of times. It would make life much easier if for sites I visit regularly, the same could be achieved by whitelisting them.

I read that an overhaul of whitelist is in the plans, so perhaps this enhancement could be implemented then.

Thanks

**Comment by piperun** [comment]
I would wager a better overhaul of how whitelisting works, would be the best solution, instead of having to write dictionary entries, you simply paste the website and check or specify which function you want to still be applied.

And also to have the option to use the "real browser" user agent instead of yet another fake user agent.

**Comment by danielcra** [comment]
I agree; it would be good to have a quick access button for whitelisting.
However my main point was: we need a way to disable all spoofing functionality of RAS, not just some.
It's really futile using trial-and-error to find out which feature it is that breaks a website.

**Comment by piperun** [comment]
Yeah true.

**Comment by dillbyrne** [comment]
This will not work at this moment in time. It will only work for headers and script injection options, which is why they are added to the whitelist . The other preferences are global and shared across the browser process. To implement this properly tabs would need their own copy of isolated preferences.
