### ISSUE TITLE
A new Firefox option to hide window.screen

### ISSUE THREAD

**Issue by BananaMangoFestival** [dillbyrne/random-agent-spoofer#456]
In about:config, adding a new boolean value "privacy.resistFingerprinting" and set it to true

You can check it to http://ip-check.info/?lang=en

But it doesn't hide "Screen", however, it's better than nothing while waiting for the new version...

**Comment by dillbyrne** [comment]
@BananaMangoFestival I already have the window.screen spoofing fixed ;) but I have not yet managed to get the spoofing of the windows attributes working again . . . . yet.

Adding that option in my case on firefox 50.0a2 (2016-08-30) did nothing to the "browser window" entry on ip-check.info .  What is it supposed to do ?

**Comment by BananaMangoFestival** [comment]
It supposed to do [this](http://image.noelshack.com/fichiers/2016/35/1472683114-1.png) on Firefox 48.0.2

So I hope you'll fix this problem, we count on you! btw, what about "window.name"? did you fix this?

**Comment by hdatma** [comment]
It works on FF-ESR 45.3.0, but also returns the screen's real size:

Screen 1051 x 694 pixels 24 bit color depth  medium
Screen (usable)   matches screen resolution  good
Browser window  matches screen resolution  good

**Comment by dillbyrne** [comment]
@BananaMangoFestival I tested it and it worked but it does not work when RAS is also spoofing the screen size. I’m guessing that preference tells the site that all the values are the same but the size is still determined by your screen size but we change this in RAS so then the window does not match.

I won't add this pref because of the issue above but once I get the window size spoofing working again it will be better that this pref since it will spoof all the attributes and not rely on the real size to do it.

Thanks for the suggestion.
