### ISSUE TITLE
Determine if SPDY support should be disabled within Firefox?

### ISSUE THREAD

**Issue by DrunkenSasquatch** [dillbyrne/random-agent-spoofer#478]
The [SPDY](https://en.wikipedia.org/wiki/SPDY) networking protocol, which is supposed to reduce load latency on webpages is yet another way of determining your real profile regardless if the user agent is spoofed. Google developed the protocol (no surprise) which is now being deprecated and support has been removed from Chrome version 51. 

As seen below, the request header shows the user agent is set to Edge, but because `network.http.spdy.enabled` is set to `true` by default, Google knows that i'm using Firefox which is seen in the response header.

![screenshot](https://cloud.githubusercontent.com/assets/16097892/19173881/0ae9ebe2-8c6e-11e6-9b09-70089b26a606.jpg)

**Comment by sueridgepipe** [comment]
What happens when `network.http.spdy.enable` is set to `false` ?  Does this alter the response header to remove Firefox browser identification?

The following settings are also available...

`network.http.spdy.enabled.deps;true`
`network.http.spdy.enabled.http2;true`
`network.http.spdy.enabled.v3-1;true`

Can these be set to 'false' also without breaking anything?

**Comment by Wannabe-Programmer** [comment]
@sueridgepipe `network.http.spdy.enabled` to `false` disables support completely. The other options are more specific I believe. `X-Firefox-spdy` will not show in the response header if support is disabled, which means your real profile cannot be detected using this method.

The reason this issue is in the form of a question is because I want to make sure that disabling support doesn't damage performance before considering to add an option for toggling in RAS. I would need an opinion from @dillbyrne and approval first.

**Comment by Wannabe-Programmer** [comment]
<b>Update:</b> I have added this option on my own branch in light of this information.

> As of July 2016, approximately 7.1% of all websites support SPDY. Fielded versions of the two most popular web servers, NGINX and Apache, are the major providers of SPDY traffic.

![spdy](https://cloud.githubusercontent.com/assets/16097892/19790011/ef92ba0a-9cf7-11e6-9947-85ee85f3b3b6.png)

**Comment by dillbyrne** [comment]
Mozilla has a patch to remove spdy/3.1 https://bugzilla.mozilla.org/show_bug.cgi?id=1248197

We could send the SPDY that each browser sends but since chrome has decided to remove it we are probably better off disabling it as the rest will follow I'd imagine.

@DrunkenSasquatch have you noticed any performance issues with it disabled ?

**Comment by DrunkenSasquatch** [comment]
@dillbyrne Hi Dillbyrne,
>have you noticed any performance issues with it disabled?

No, nothing that is recognizable to me. Perhaps a few milliseconds of page loading but nothing that can be recognized by any human being in my opinion. 

The spdy/3.1 option is more specific i believe and has disabled by default since FF-50. However, the primary kill-switch is `network.http.spdy.enabled`. if you want, I can submit a PR for a toggle option to save you the effort?

**Comment by dillbyrne** [comment]
Closing this as @DrunkenSasquatch  has added an option to disable it #501
