### ISSUE TITLE
Accept-Language & Accept-Encoding

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#484]
Can you please explain Accept-Language? I have read the Wiki and this does not make sense.

For English as example the default is `en-US` and enabled it's changed to `en-US,en;q=0.5`, why is this of benefit? From what I understand, from a fingerprint standppoint the Accept-Language enabled creating `en-US,en;q=0.5` is not good. Even Tor doesn't do this from a Anonymous aspect, so I'm not sure why this is being considered a good thing in RAS?

Also Accept-Encoding doesn't make sense, with it disabled we have this;

gzip,deflate

With it enabled, it only creates a space like this;

gzip, deflate

**Comment by dillbyrne** [comment]
The accept headers change depending on the browser used and depending on your accept language choice. 

The accept language header tells a page which language you would prefer to see the page in,  if the page is localised that is.  Each browser has different default values for each language of the accept headers. 

I'm waiting on non en-US chrome / opera / edge users to submit their default accept language headers and I can add them to the chrome profiles. They must be the default for their country though.

So if you look at the [Profiles file](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json) file you will see chrome / opera , edge and firefox/seamonkey differ. In firefox because I know they release the browser in different languages I have added the option to change the accept language. https://www.mozilla.org/en-US/firefox/all/

https://github.com/dillbyrne/random-agent-spoofer/wiki/Profiles-Explained

All the possible language choices are the default versions. `en-US,en;q=0.5` is the default US english option for firefox and tor browser.

the space in accept encoding is displayed by default 
http://pgl.yoyo.org/http/browser-headers.php
http://browserspy.dk/headers.php

**Comment by Geyup** [comment]
@dillbyrne you forgot to reply regarding ```gzip,deflate``` which I mentioned the only change is a space created...

hmm

**Comment by dillbyrne** [comment]
>@dillbyrne you forgot to reply regarding gzip,deflate which I mentioned the only change is a space created...

>hmm


Read my initial reply and see the last three lines

The space should be fault in firefox and chrome profiles. I need to double check Opera again but I'd imagine it also has spaces due to the webkit base.

**Comment by Geyup** [comment]
SORRY my bad... :(

thanks
