### ISSUE TITLE
Firefox Quantum disabled Random Agent Spoofer without switching it off

### ISSUE THREAD

**Issue by theologian42** [dillbyrne/random-agent-spoofer#585]
Thus, my browser (Firefox, Windows 10) is stuck with the wrong headers (Chrome, OS X). I have tried restarting Firefox and Windows, but to no avail. This means I cannot download Firefox extensions. How do I set it back to the correct profile?

**Comment by gitbugged** [comment]
Solution 1): Downgrade to Firefox 52 ESR. (Recommended until Mozilla gets their head out from their behind and stops ruining all privacy addons by design), and [don't use Windows 10](https://www.privacytools.io/#win10).

Solution 2): From your current installation, type in the address bar: about:config, say ok to the prompt, then type "general.useragent.override", and set this variable to blank.

**Comment by theologian42** [comment]
Solution 1 is a complete non-starter. Solution 2 leads to a browser not supported error in Facebook, although other sites work. Any other ideas?

**Comment by theologian42** [comment]
addons.mozilla.com doesn't recognise it as Firefox either.

**Comment by theologian42** [comment]
So: I have managed to get back to stability by copying settings from my laptop, so it now thinks I am running Safari on Linux.

The relevant keys appear to be:
general.appname.override
general.appversion.override
general.platform.override
general.useragent.override
general.useragent.vendor

Can anyone suggest settings for them that don't break Firefox?

**Comment by GenericHuman** [comment]
I had to refresh Firefox. You lose your extensions but it works and changing your extensions is broken otherwise anyway.

**Comment by theologian42** [comment]
In fact, the solution is blindingly obvious. reset all five keys to their default values and the problem goes away.
