### ISSUE TITLE
Feature request: White listing

### ISSUE THREAD

**Issue by dagaz** [dillbyrne/random-agent-spoofer#81]
Hello!

Ich have a feature request: It would be really nice if there was a white list for sites where spoofing is always turned off. Some sites really dont work - and sometimes I fotget to turn on spoofing again. Another thing: Sometimes I am on sites which I want to be spoofed and in different tabs on sites which sould not be spoofed.

So a white list would be really useful.

**Comment by Mosrite** [comment]
Whitelisting doesn't seem to work properly for all domains. E.g. I cannot see the actual map on openstreetmap.org if RAS is enabled, even though I whitlisted the domain completely. Same goes for German journalism project krautreporter.de: I cannot see articles as long as RAS is enabled. Whitelisting the domain doesn't make any difference.

**Comment by dillbyrne** [comment]
Hello @Mosrite 

I'm aware the whitelist needs work. Especially concerning the UI and sites that make third party requests. I intend to deal with the latter after multiprocess functionality has landed in firefox and the codebase is stable and when that is done I'll update the UI around that.


As for your current concern I have not encounter any problems on either sites you mentioned. I didn't have to whitelist anything 

Open Street Map with RAS 0.9.5.1 everything blocked and set to random desktop
![ras_preview3](https://cloud.githubusercontent.com/assets/2903711/6866852/30bdf006-d474-11e4-81c4-eafd1b7fdd0f.png)

Open Street Map with current Dev version of RAS up to latest commit just to test it. Everything enabled and no whitelist is in use
![ras_preview5](https://cloud.githubusercontent.com/assets/2903711/6866891/7bb9c29c-d474-11e4-8e57-378005f6d2ad.png)


RAS 0.9.5.1 on  krautreporter.de
![ras_preview4](https://cloud.githubusercontent.com/assets/2903711/6866931/d857c59e-d474-11e4-92ce-313ace6a1ad9.png)

I cannot reproduce this in two separate instances with different versions of RAS. That would suggest the problem lies elsewhere, perhaps with another addon ?

**Comment by Mosrite** [comment]
Hmm, that's odd. These sites only work for me when I disable RAS completely. Maybe it is because I use the beta version of Firefox? But if you cannot reproduce this error just ignore it.
